#ifndef __PAH8SERIES_DATA_C_H__
#define __PAH8SERIES_DATA_C_H__

#include <stdint.h>

typedef struct {
    uint8_t                     frame_count;
    uint32_t                    time;
    uint8_t                     touch_flag;
    uint32_t                    nf_ppg_channel;
    uint32_t                    nf_ppg_per_channel;
    int32_t                     *ppg_data;
    uint32_t                    nf_mems;
    int16_t                     *mems_data;
} pah8series_data_t;

typedef enum {
    PAH8SERIES_PARAM_IDX_SAMPLE_RATE = 0,
    PAH8SERIES_PARAM_IDX_GSENSOR_MODE,
    PAH8SERIES_PARAM_IDX_PPG_CH_NUM,
    PAH8SERIES_PARAM_IDX_HAS_IR_CH,
    PAH8SERIES_PARAM_IDX_SIGNAL_GRADE,
    PAH8SERIES_PARAM_IDX_IIR_SMOOTH_PRED,
    PAH8SERIES_PARAM_IDX_IIR_LP,
    PAH8SERIES_PARAM_IDX_FIRST_HR_MULTIPLE_OFFSET_MEMS_THR,
    PAH8SERIES_PARAM_IDX_FIRST_HR_IN_MOTION_FLAG,
    PAH8SERIES_PARAM_IDX_FIRST_HR_MEMS_QUALITY_THR,
    PAH8SERIES_PARAM_IDX_FIRST_HR_PPG_QUALITY_THR,
    PAH8SERIES_PARAM_IDX_STATIC_MODE,
    PAH8SERIES_PARAM_IDX_STATIC_HR_UP_IDX,
    PAH8SERIES_PARAM_IDX_STATIC_HR_DN_IDX,
    PAH8SERIES_PARAM_IDX_IS_AUTO,
    PAH8SERIES_PARAM_IDX_IS_TAG,
    PAH8SERIES_PARAM_IDX_IS_8002,
    PAH8SERIES_PARAM_IDX_FIRST_HR_6SEC,
    PAH8SERIES_PARAM_IDX_HR_MODEL_TIME_CONST,
    PAH8SERIES_PARAM_IDX_HR_MODEL_PROGRESS_RATIO,
    PAH8SERIES_PARAM_IDX_INIT_WALK_HR,
    PAH8SERIES_PARAM_IDX_WALK_HR_UP_IDX,
    PAH8SERIES_PARAM_IDX_WALK_HR_DN_IDX,
    PAH8SERIES_PARAM_IDX_HR_TOO_LOW_IDX,
    PAH8SERIES_PARAM_IDX_EN_LWPS,
    PAH8SERIES_PARAM_IDX_EN_JUDGE_WALK,
    PAH8SERIES_PARAM_IDX_EN_CHK_HR_GT_MOTION,
    PAH8SERIES_PARAM_IDX_EN_HI_QUALITY_HR_JMP,
    PAH8SERIES_PARAM_IDX_EN_SPLIT_MOTION_PEAK,
    PAH8SERIES_PARAM_IDX_EN_LOCAL_FIRST_PEAK_TRACK,
    PAH8SERIES_PARAM_IDX_LOCAL_FIRST_PEAK_FRM_ALIVE_THR,
    PAH8SERIES_PARAM_IDX_EN_GLOBAL_FIRST_PEAK_TRACK,
    PAH8SERIES_PARAM_IDX_GLOBAL_FIRST_PEAK_FRM_ALIVE_THR,
    PAH8SERIES_PARAM_IDX_EN_FORCE_HR_OUT_IN10S,
    PAH8SERIES_PARAM_IDX_DEFAULT_HR_OUT_IN10S,
    PAH8SERIES_PARAM_IDX_FIRST_HR_HALF_1X_ENERGY_THT,
    PAH8SERIES_PARAM_IDX_HR_IN_MOTION_SEARCH_ST,
    PAH8SERIES_PARAM_IDX_HR_IN_MOTION_SEARCH_END,
    PAH8SERIES_PARAM_IDX_EN_MA_WALK,
    PAH8SERIES_PARAM_IDX_EN_HAND_CLAP,
    PAH8SERIES_PARAM_IDX_EN_NOR_PRE_DIFF_NOR,
    PAH8SERIES_PARAM_IDX_EN_HALF_HR_CHK,
    PAH8SERIES_PARAM_IDX_EN_NON_MOTION_FIRST_PEAK_TRACK,
    PAH8SERIES_PARAM_IDX_NON_MOTION_FIRST_PEAK_ALIVE_FRM_THR,
    PAH8SERIES_PARAM_IDX_PPG_NORMALIZE_LEN,
    PAH8SERIES_PARAM_IDX_PPG_DIFF_NORMALIZE_LEN,
    PAH8SERIES_PARAM_IDX_EN_CHK_HQ_3X_PPG,
    PAH8SERIES_PARAM_IDX_EN_POST_HR_PROCESS,
    //v519
    PAH8SERIES_PARAM_IDX_SET_EN_JAFMI,
    PAH8SERIES_PARAM_IDX_SET_EN_TIME_DOMAIN_CONFIRM,
    PAH8SERIES_PARAM_IDX_SET_RESERVE_PEAK_RATIO_THR,
    PAH8SERIES_PARAM_IDX_SET_SUPPORT_HR_IDX_OFFSET,
    PAH8SERIES_PARAM_IDX_SET_SUPPORT_CHECK_STEP_FREQ,
    //v520
    PAH8SERIES_PARAM_IDX_SET_SUPPORT_FOUND_HR_IDX,
    PAH8SERIES_PARAM_IDX_SET_SUPPORT_SIGNAL_LEVEL_CHECK,
    //v521
    PAH8SERIES_PARAM_IDX_SET_FORCE_OUT_SAMPLE_COUNT_10S,
    //v526
    PAH8SERIES_PARAM_IDX_SET_FLAG_LIMIT_HR_UB,
    PAH8SERIES_PARAM_IDX_SET_LIMIT_HR_UB,
    //v528
    PAH8SERIES_PARAM_IDX_SET_SUPPORT_FAST_POST_HR_IDX_FLAG,
    //v532
    PAH8SERIES_PARAM_IDX_SET_FLAG_LIMIT_HR_LB,
    PAH8SERIES_PARAM_IDX_SET_LIMIT_HR_LB,
	//V534 pre06	
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_ONHAND_RECONIZATION,
	//V536 pre00
	PAH8SERIES_PARAM_IDX_SET_LINIT_HROUT_LB,
	PAH8SERIES_PARAM_IDX_SET_LINIT_HROUT_UB,
	//V537 pre06
	PAH8SERIES_PARAM_IDX_SET_DYNAMIC_HR_RATIO,		//V536 pre04
	PAH8SERIES_PARAM_IDX_SET_IIR_LP2_ALPHA,
	//V538 pre04
	PAH8SERIES_PARAM_IDX_SET_SIGNAL_GRADE_ONDASK_THR,		//V536 pre01
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_ARMSWING_RECOGNIZATION,
	//V5363
	PAH8SERIES_PARAM_IDX_SET_HROUT_TRUST_ENH,
	PAH8SERIES_PARAM_IDX_SET_HROUT_TRUST_UB,
	//V536 pre04
	PAH8SERIES_PARAM_IDX_SET_SIG_LEVEL_GOOD_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_SIG_LEVEL_GOOD_MODE,
	//V538 pre24
	PAH8SERIES_PARAM_IDX_SET_TRUSE_LEVEL_EQMOTION,
	//V539 pre25
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_RE_INIT_HR_30S,
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_DOUBLE_EA,
	PAH8SERIES_PARAM_IDX_SET_DOUBLE_EA_ALPHA,
	PAH8SERIES_PARAM_IDX_SET_DOUBLE_EA_BETA,
	PAH8SERIES_PARAM_IDX_SET_FLAG_PREDICTION_FEEDBACK,
	PAH8SERIES_PARAM_IDX_SET_FEEDBACK_GLITCH_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_FEEDBACK_TRUST_LEVEL_TH,
	PAH8SERIES_PARAM_IDX_SET_FEEDBACK_LEN_PRED_SHORT,
	PAH8SERIES_PARAM_IDX_SET_FEEDBACK_LEN_PRED_LONG,
	PAH8SERIES_PARAM_IDX_SET_FLAG_PREDICTION_SMOOTH,
	PAH8SERIES_PARAM_IDX_SET_SMOOTH_GLITCH_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_SMOOTH_TRUST_LEVEL_TH,
	PAH8SERIES_PARAM_IDX_SET_SMOOTH_LEN_PRED_SHORT,
	PAH8SERIES_PARAM_IDX_SET_SMOOTH_LEN_PRED_LONG,
	PAH8SERIES_PARAM_IDX_SET_SKIP_DATA_LEN,
	PAH8SERIES_PARAM_IDX_SET_FLAG_MEMS_3_SEP,
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_SUPER_LOW_INIT_HR,
	//V541 pre10
	PAH8SERIES_PARAM_IDX_SET_FLAG_BIKE_MODE,
	PAH8SERIES_PARAM_IDX_SET_MOTION_RMS_GS_THR,
	//V542 pre05
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_LIMIT_HR_UB_BY_MEMS,
	PAH8SERIES_PARAM_IDX_SET_LIMIT_HR_UB_MEMS_TH,
	PAH8SERIES_PARAM_IDX_SET_LIMIT_HR_UB_BY_MEMS,
	//V543 pre06
	PAH8SERIES_PARAM_IDX_SET_HR_STEP_FREQ_MIXED_DIFF_IDX_TH,
	//V543 pre08
	PAH8SERIES_PARAM_IDX_SET_STATIC_MEMS_FFT_ENERGY_TH,
	//V544 pre07
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_LIMIT_HR_DIFF,
	PAH8SERIES_PARAM_IDX_SET_LIMIT_HR_DIFF,
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_FORCE_HR_FOLLOW_MEMS,
	PAH8SERIES_PARAM_IDX_SET_COUNT_DASK_TRANS_TO_HAND_TH,
	//V546 pre03
	PAH8SERIES_PARAM_IDX_SET_FLAG_MEMS_3_SWITCH,
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_DY_HR_CLEAN_SPEC_AND_MOTION_IDX_FIX,
	PAH8SERIES_PARAM_IDX_SET_NO_MOVE_JMP_DIFF_IDX,
	PAH8SERIES_PARAM_IDX_SET_MOTION_JMP_DIFF_IDX_THR,
	//V548 pre02
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_CHANNEL_QUALITY,
	PAH8SERIES_PARAM_IDX_SET_FLAG_TIME_DOMAIN_INIT_HR_DETECTION,
	PAH8SERIES_PARAM_IDX_SET_FORCE_HR_FOLLOW_MEMS_UP_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_FORCE_HR_FOLLOW_MEMS_DN_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_FLAG_DYNAMIC_HR_RATIO_SWITCH,
	PAH8SERIES_PARAM_IDX_SET_DYNAMIC_HR_REG_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_DYNAMIC_HR_RATIO_REG,
	//V549 pre04
	PAH8SERIES_PARAM_IDX_SET_FLAG_EN_SWIMMING_FINE_TUNING,
	PAH8SERIES_PARAM_IDX_SET_FALG_INIT_HR_LBUB_BY_SIG_QUAL,
	PAH8SERIES_PARAM_IDX_SET_FALG_INIT_HR_LBUB_BY_SIG_QUAL_TH,
	PAH8SERIES_PARAM_IDX_SET_FALG_INIT_HR_BETWEEN_LBUB,
	PAH8SERIES_PARAM_IDX_SET_FALG_IMP,
	PAH8SERIES_PARAM_IDX_SET_INIT_HR_LBUB_RATIO,
	//V550
	PAH8SERIES_PARAM_IDX_SUPPORT_DYNAMIC_HR_STATE_SWITCH,
	//V551
	PAH8SERIES_PARAM_IDX_SET_TRUST_LEVEL_SKIP_ZERO_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_MOTION_JMP_DIFF_IDX_THR0,
	PAH8SERIES_PARAM_IDX_SET_MOTION_JMP_DIFF_IDX_THR1,
	//V552
	PAH8SERIES_PARAM_IDX_SET_ADPTIVE_RLS_ORDER,
	PAH8SERIES_PARAM_IDX_SET_FLAG_PREDICTION_FEEDBACK_DATA_COUNT,
	PAH8SERIES_PARAM_IDX_SET_FLAG_PREDICTION_FEEDBACK_HR_LIMIT,
	PAH8SERIES_PARAM_IDX_SET_FLAG_PREDICTION_FEEDBACK_SIGNAL_QUALITY,
	//V552 pre04
	PAH8SERIES_PARAM_IDX_SET_CHECK_SIGNAL_LEVEL_JMP_COUNT_TH,
	PAH8SERIES_PARAM_IDX_SET_FLAG_CHECK_SIGNAL_LEVEL_EXCLUDE_MOTION_FREQ,
	//V553 pre09
	PAH8SERIES_PARAM_IDX_SET_FLAG_SUPPORT_AUTOCORRELATION,
	PAH8SERIES_PARAM_IDX_SET_DYNAMIC_PPG_NORMALIZE_LEN,
	//V553 pre11
	PAH8SERIES_PARAM_IDX_SET_FLAG_SUPPORT_FFT120,
	PAH8SERIES_PARAM_IDX_SET_IIR_FILTER_OUT_PRED_THR,
	PAH8SERIES_PARAM_IDX_SET_IIR_FILTER_OUT_PRED_VALUE,
	PAH8SERIES_PARAM_IDX_SET_IIR_FILTER_OUT_PRED_RATIO,
    PAH8SERIES_NF_PARAM_IDX,
} pah8series_param_idx_t;

typedef enum {
    MSG_SUCCESS = 0,
    MSG_ALG_NOT_OPEN,
    MSG_ALG_REOPEN,
    MSG_MEMS_LEN_TOO_SHORT,
    MSG_NO_TOUCH,
    MSG_PPG_LEN_TOO_SHORT,
    MSG_FRAME_LOSS,
    MSG_INVALID_ARGUMENT,
	MSG_PROCESS_NOT_FINISHED,
	MSG_ADDR_NOT_4BYTE_ALIGNED,

    MSG_NO_MEM = 14,
    MSG_ECG_LEN_TOO_SHORT = 15,

    MSG_HR_READY = 0x30,
    MSG_SIGNAL_POOR = 0x40
} pah8series_msg_code_t;


#endif // PAH8002_DATA_H__
