#ifndef __DATA_SERVICE_CUSTOM_H__
#define __DATA_SERVICE_CUSTOM_H__
#include "gx_api.h"
typedef enum {
	DATA_SERVICE_EVT_BRIGHTNESS_CHG = GX_FIRST_USER_EVENT,
	DATA_SERVICE_EVT_BRIGHT_TIME_CHG,
	DATA_SERVICE_EVT_ALARM_INFO_CHG,
	DATA_SERVICE_EVT_REMINDERS_INFO_CHG,
	DATA_SERVICE_EVT_STOP_WATCH_INFO_CHG,
} DATA_SERVICE_EVT_TYPE;

void data_service_event_submit(DATA_SERVICE_EVT_TYPE evt_type, void *data, uint8_t data_size);

#endif