/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.6.1                                               */
/*  Date (dd.mm.yyyy): 20. 4.2021   Time (hh:mm): 09:19                        */
/*******************************************************************************/

#include "gx_api.h"
#include "guix_simple_resources.h"
#include "guix_language_resources_custom.h"

/* String values                                                               */
GX_CONST GX_UBYTE main_display_STRING_1_English[] = "hello";
GX_CONST GX_UBYTE main_display_STRING_1_Chinese[] = "你好";

/* String Table for honbow_disp language English                               */
GX_CONST GX_STRING honbow_disp_English_string_table[HONBOW_DISP_STRING_TABLE_SIZE_CUSTOM] = {
	{GX_NULL, 0},
	{(GX_CONST GX_CHAR *)main_display_STRING_1_English, sizeof(main_display_STRING_1_English) - 1},
};

/* String Table for honbow_disp language Chinese                               */
GX_CONST GX_STRING honbow_disp_Chinese_string_table[HONBOW_DISP_STRING_TABLE_SIZE_CUSTOM] = {
	{GX_NULL, 0},
	{(GX_CONST GX_CHAR *)main_display_STRING_1_Chinese, sizeof(main_display_STRING_1_Chinese) - 1},
};

/*  Language Table                                                             */
GX_CONST GX_STRING *honbow_disp_language_table[HONBOW_DISP_LANGUAGE_TABLE_SIZE_CUSTOM] = {
	[LANGUAGE_ENGLISH] = honbow_disp_English_string_table,
	[LANGUAGE_CHINESE] = honbow_disp_Chinese_string_table,
};
