#ifndef __GUIX_LANGUAGE_RESOURCE_CUSTOM_H__
#define __GUIX_LANGUAGE_RESOURCE_CUSTOM_H__

#define HONBOW_DISP_LANGUAGE_TABLE_SIZE_CUSTOM 2
#define HONBOW_DISP_STRING_TABLE_SIZE_CUSTOM 2

#define LANGUAGE_ENGLISH 0
#define LANGUAGE_CHINESE 1

#define GX_STRING_ID_HELLO 1 // add for example

#endif