#ifndef ZEPHYR_INCLUDE_DRIVERS_EXT_SENSOR_PRIV_H_
#define ZEPHYR_INCLUDE_DRIVERS_EXT_SENSOR_PRIV_H_

#include <drivers/sensor.h>

enum sensor_channel_ext {
	SENSOR_CHAN_HEART_RATE = SENSOR_CHAN_PRIV_START + 1,
	SENSOR_CHAN_SPO2,
	SENSOR_CHAN_BATTERY_CHARGE_STATUS,
	SENSOR_CHAN_BATTERY_CAPACITY,
};

enum sensor_attribute_ext {
	SENSOR_ATTR_SENSOR_START_STOP = SENSOR_ATTR_PRIV_START + 1,
	SENSOR_ATTR_START,
	SENSOR_ATTR_STOP,

	/* Charge sensor */
	SENSOR_ATTR_SET_SHIPPING_MODE,
	SENSOR_ATTR_SET_CHARGE_EN,
	SENSOR_ATTR_SET_VSYS_VOLTAGE,

};

enum sensor_trigger_type_ext {
	/* Charge sensor */
	SENSOR_TRIG_CHARGE_IN     = SENSOR_TRIG_PRIV_START + 1,
	SENSOR_TRIG_CHARGE_OUT,
	SENSOR_TRIG_CHARGE_FINISH,
	SENSOR_TRIG_CHARGE_OV,
	SENSOR_TRIG_CHARGE_OT,
	SENSOR_TRIG_CHARGE_UT,
};
#endif