#ifndef BASE_EV_TYPES_H_
#define BASE_EV_TYPES_H_

#include "base/evmgr.h"

#define USER_EVENT(ev) ((ev) + GX_FIRST_APP_EVENT)

enum ev_types {
    EV_MESSAGE,
    EV_OTA,
    EV_LOW_POWER,
    EV_CHARGING,
    EV_GOAL1_COMPLETED,
    EV_GOAL2_COMPLETED,
    EV_GOAL3_COMPLETED,
    EV_GOAL4_COMPLETED,
    EV_SEDENTARINESS,
    EV_HEARTRATE_ALERT,
    EV_ALARM_ALERT,
    EV_SHUTDOWN,
    EV_SHUTDOWN_ANI,
    EV_SPORTING,
    EV_RINGING
};

#define EV_PRIO_MESSAGE            EV_TYPE(6, EV_MESSAGE)
#define EV_PRIO_OTA                EV_TYPE(1, EV_OTA)
#define EV_PRIO_LOW_POWER          EV_TYPE(2, EV_LOW_POWER)
#define EV_PRIO_CHARGING           EV_TYPE(2, EV_CHARGING)
#define EV_PRIO_GOAL1_COMPLETED    EV_TYPE(11, EV_GOAL1_COMPLETED)
#define EV_PRIO_GOAL2_COMPLETED    EV_TYPE(11, EV_GOAL2_COMPLETED)
#define EV_PRIO_GOAL3_COMPLETED    EV_TYPE(11, EV_GOAL3_COMPLETED)
#define EV_PRIO_GOAL4_COMPLETED    EV_TYPE(11, EV_GOAL4_COMPLETED)
#define EV_PRIO_SEDENTARINESS      EV_TYPE(8, EV_SEDENTARINESS)
#define EV_PRIO_HEARTRATE_ALERT    EV_TYPE(5, EV_HEARTRATE_ALERT)
#define EV_PRIO_ALARM_ALERT        EV_TYPE(4, EV_ALARM_ALERT)
#define EV_PRIO_SHUTDOWN           EV_TYPE(XX, EV_SHUTDOWN)
#define EV_PRIO_SHUTDOWN_ANI       EV_TYPE(XX, EV_SHUTDOWN_ANI)
#define EV_PRIO_SPORTING           EV_TYPE(10, EV_SPORTING)
#define EV_PRIO_RINGING            EV_TYPE(3, EV_RINGING)


#endif /* BASE_EV_TYPES_H_ */
