#ifndef __APP_SETTING_H__
#define __APP_SETTING_H__

typedef enum {
	SETTING_CHILD_PAGE_DISP = 0,
	SETTING_CHILD_PAGE_APP_VIEW,
	SETTING_CHILD_PAGE_DND,
	SETTING_CHILD_PAGE_VIB_TUNER,
	SETTING_CHILD_PAGE_TRAINING_DETECT,
	SETTING_CHILD_PAGE_MUSIC_CTRL,
	SETTING_CHILD_PAGE_SYSTEM,
} SETTING_CHILD_PAGE_T;

#endif