/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: call.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "call.pb-c.h"
void   call__notice__init
                     (Call__Notice         *message)
{
  static const Call__Notice init_value = CALL__NOTICE__INIT;
  *message = init_value;
}
size_t call__notice__get_packed_size
                     (const Call__Notice *message)
{
  assert(message->base.descriptor == &call__notice__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t call__notice__pack
                     (const Call__Notice *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &call__notice__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t call__notice__pack_to_buffer
                     (const Call__Notice *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &call__notice__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Call__Notice *
       call__notice__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Call__Notice *)
     protobuf_c_message_unpack (&call__notice__descriptor,
                                allocator, len, data);
}
void   call__notice__free_unpacked
                     (Call__Notice *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &call__notice__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   call__call_state__init
                     (Call__CallState         *message)
{
  static const Call__CallState init_value = CALL__CALL_STATE__INIT;
  *message = init_value;
}
size_t call__call_state__get_packed_size
                     (const Call__CallState *message)
{
  assert(message->base.descriptor == &call__call_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t call__call_state__pack
                     (const Call__CallState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &call__call_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t call__call_state__pack_to_buffer
                     (const Call__CallState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &call__call_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Call__CallState *
       call__call_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Call__CallState *)
     protobuf_c_message_unpack (&call__call_state__descriptor,
                                allocator, len, data);
}
void   call__call_state__free_unpacked
                     (Call__CallState *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &call__call_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor call__notice__field_descriptors[3] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Call__Notice, timestamp),
    &proto__time__unix_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Call__Notice, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "people",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Call__Notice, people),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned call__notice__field_indices_by_name[] = {
  2,   /* field[2] = people */
  1,   /* field[1] = phone */
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange call__notice__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor call__notice__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "call.Notice",
  "Notice",
  "Call__Notice",
  "call",
  sizeof(Call__Notice),
  3,
  call__notice__field_descriptors,
  call__notice__field_indices_by_name,
  1,  call__notice__number_ranges,
  (ProtobufCMessageInit) call__notice__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue call__call_state__state__enum_values_by_number[3] =
{
  { "ANSWER", "CALL__CALL_STATE__STATE__ANSWER", 1 },
  { "REJECT", "CALL__CALL_STATE__STATE__REJECT", 2 },
  { "SPEAKER", "CALL__CALL_STATE__STATE__SPEAKER", 3 },
};
static const ProtobufCIntRange call__call_state__state__value_ranges[] = {
{1, 0},{0, 3}
};
static const ProtobufCEnumValueIndex call__call_state__state__enum_values_by_name[3] =
{
  { "ANSWER", 0 },
  { "REJECT", 1 },
  { "SPEAKER", 2 },
};
const ProtobufCEnumDescriptor call__call_state__state__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "call.CallState.State",
  "State",
  "Call__CallState__State",
  "call",
  3,
  call__call_state__state__enum_values_by_number,
  3,
  call__call_state__state__enum_values_by_name,
  1,
  call__call_state__state__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor call__call_state__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Call__CallState, state),
    &call__call_state__state__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned call__call_state__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange call__call_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor call__call_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "call.CallState",
  "CallState",
  "Call__CallState",
  "call",
  sizeof(Call__CallState),
  1,
  call__call_state__field_descriptors,
  call__call_state__field_indices_by_name,
  1,  call__call_state__number_ranges,
  (ProtobufCMessageInit) call__call_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
