/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: factory.proto */

#ifndef PROTOBUF_C_factory_2eproto__INCLUDED
#define PROTOBUF_C_factory_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Factory__FactoryTest Factory__FactoryTest;
typedef struct _Factory__HeartRateTest Factory__HeartRateTest;


/* --- enums --- */


/* --- messages --- */

struct  _Factory__FactoryTest
{
  ProtobufCMessage base;
  protobuf_c_boolean enable;
};
#define FACTORY__FACTORY_TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&factory__factory_test__descriptor) \
    , 0 }


/*
 *Respond for heartrate test command
 */
struct  _Factory__HeartRateTest
{
  ProtobufCMessage base;
  /*
   * Heartrate 
   */
  uint32_t hr;
  /*
   * Blood oxygen 
   */
  uint32_t bo;
};
#define FACTORY__HEART_RATE_TEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&factory__heart_rate_test__descriptor) \
    , 0, 0 }


/* Factory__FactoryTest methods */
void   factory__factory_test__init
                     (Factory__FactoryTest         *message);
size_t factory__factory_test__get_packed_size
                     (const Factory__FactoryTest   *message);
size_t factory__factory_test__pack
                     (const Factory__FactoryTest   *message,
                      uint8_t             *out);
size_t factory__factory_test__pack_to_buffer
                     (const Factory__FactoryTest   *message,
                      ProtobufCBuffer     *buffer);
Factory__FactoryTest *
       factory__factory_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   factory__factory_test__free_unpacked
                     (Factory__FactoryTest *message,
                      ProtobufCAllocator *allocator);
/* Factory__HeartRateTest methods */
void   factory__heart_rate_test__init
                     (Factory__HeartRateTest         *message);
size_t factory__heart_rate_test__get_packed_size
                     (const Factory__HeartRateTest   *message);
size_t factory__heart_rate_test__pack
                     (const Factory__HeartRateTest   *message,
                      uint8_t             *out);
size_t factory__heart_rate_test__pack_to_buffer
                     (const Factory__HeartRateTest   *message,
                      ProtobufCBuffer     *buffer);
Factory__HeartRateTest *
       factory__heart_rate_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   factory__heart_rate_test__free_unpacked
                     (Factory__HeartRateTest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Factory__FactoryTest_Closure)
                 (const Factory__FactoryTest *message,
                  void *closure_data);
typedef void (*Factory__HeartRateTest_Closure)
                 (const Factory__HeartRateTest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor factory__factory_test__descriptor;
extern const ProtobufCMessageDescriptor factory__heart_rate_test__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_factory_2eproto__INCLUDED */
