/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: factory.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "factory.pb-c.h"
void   factory__factory_test__init
                     (Factory__FactoryTest         *message)
{
  static const Factory__FactoryTest init_value = FACTORY__FACTORY_TEST__INIT;
  *message = init_value;
}
size_t factory__factory_test__get_packed_size
                     (const Factory__FactoryTest *message)
{
  assert(message->base.descriptor == &factory__factory_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t factory__factory_test__pack
                     (const Factory__FactoryTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &factory__factory_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t factory__factory_test__pack_to_buffer
                     (const Factory__FactoryTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &factory__factory_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Factory__FactoryTest *
       factory__factory_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Factory__FactoryTest *)
     protobuf_c_message_unpack (&factory__factory_test__descriptor,
                                allocator, len, data);
}
void   factory__factory_test__free_unpacked
                     (Factory__FactoryTest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &factory__factory_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   factory__heart_rate_test__init
                     (Factory__HeartRateTest         *message)
{
  static const Factory__HeartRateTest init_value = FACTORY__HEART_RATE_TEST__INIT;
  *message = init_value;
}
size_t factory__heart_rate_test__get_packed_size
                     (const Factory__HeartRateTest *message)
{
  assert(message->base.descriptor == &factory__heart_rate_test__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t factory__heart_rate_test__pack
                     (const Factory__HeartRateTest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &factory__heart_rate_test__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t factory__heart_rate_test__pack_to_buffer
                     (const Factory__HeartRateTest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &factory__heart_rate_test__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Factory__HeartRateTest *
       factory__heart_rate_test__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Factory__HeartRateTest *)
     protobuf_c_message_unpack (&factory__heart_rate_test__descriptor,
                                allocator, len, data);
}
void   factory__heart_rate_test__free_unpacked
                     (Factory__HeartRateTest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &factory__heart_rate_test__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor factory__factory_test__field_descriptors[1] =
{
  {
    "enable",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Factory__FactoryTest, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned factory__factory_test__field_indices_by_name[] = {
  0,   /* field[0] = enable */
};
static const ProtobufCIntRange factory__factory_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor factory__factory_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "factory.FactoryTest",
  "FactoryTest",
  "Factory__FactoryTest",
  "factory",
  sizeof(Factory__FactoryTest),
  1,
  factory__factory_test__field_descriptors,
  factory__factory_test__field_indices_by_name,
  1,  factory__factory_test__number_ranges,
  (ProtobufCMessageInit) factory__factory_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor factory__heart_rate_test__field_descriptors[2] =
{
  {
    "hr",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Factory__HeartRateTest, hr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bo",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Factory__HeartRateTest, bo),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned factory__heart_rate_test__field_indices_by_name[] = {
  1,   /* field[1] = bo */
  0,   /* field[0] = hr */
};
static const ProtobufCIntRange factory__heart_rate_test__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor factory__heart_rate_test__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "factory.HeartRateTest",
  "HeartRateTest",
  "Factory__HeartRateTest",
  "factory",
  sizeof(Factory__HeartRateTest),
  2,
  factory__heart_rate_test__field_descriptors,
  factory__heart_rate_test__field_indices_by_name,
  1,  factory__heart_rate_test__number_ranges,
  (ProtobufCMessageInit) factory__heart_rate_test__init,
  NULL,NULL,NULL    /* reserved[123] */
};
