/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gps.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gps.pb-c.h"
void   gps__request__init
                     (Gps__Request         *message)
{
  static const Gps__Request init_value = GPS__REQUEST__INIT;
  *message = init_value;
}
size_t gps__request__get_packed_size
                     (const Gps__Request *message)
{
  assert(message->base.descriptor == &gps__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps__request__pack
                     (const Gps__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps__request__pack_to_buffer
                     (const Gps__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gps__Request *
       gps__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gps__Request *)
     protobuf_c_message_unpack (&gps__request__descriptor,
                                allocator, len, data);
}
void   gps__request__free_unpacked
                     (Gps__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   gps__position__init
                     (Gps__Position         *message)
{
  static const Gps__Position init_value = GPS__POSITION__INIT;
  *message = init_value;
}
size_t gps__position__get_packed_size
                     (const Gps__Position *message)
{
  assert(message->base.descriptor == &gps__position__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t gps__position__pack
                     (const Gps__Position *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &gps__position__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t gps__position__pack_to_buffer
                     (const Gps__Position *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &gps__position__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Gps__Position *
       gps__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Gps__Position *)
     protobuf_c_message_unpack (&gps__position__descriptor,
                                allocator, len, data);
}
void   gps__position__free_unpacked
                     (Gps__Position *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &gps__position__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue gps__request__start_mode__enum_values_by_number[2] =
{
  { "ONESHOT", "GPS__REQUEST__START_MODE__ONESHOT", 0 },
  { "PERIOD", "GPS__REQUEST__START_MODE__PERIOD", 1 },
};
static const ProtobufCIntRange gps__request__start_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex gps__request__start_mode__enum_values_by_name[2] =
{
  { "ONESHOT", 0 },
  { "PERIOD", 1 },
};
const ProtobufCEnumDescriptor gps__request__start_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "gps.Request.StartMode",
  "StartMode",
  "Gps__Request__StartMode",
  "gps",
  2,
  gps__request__start_mode__enum_values_by_number,
  2,
  gps__request__start_mode__enum_values_by_name,
  1,
  gps__request__start_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Gps__Request__StartMode gps__request__mode__default_value = GPS__REQUEST__START_MODE__ONESHOT;
static const ProtobufCFieldDescriptor gps__request__field_descriptors[2] =
{
  {
    "mode",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Gps__Request, mode),
    &gps__request__start_mode__descriptor,
    &gps__request__mode__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "period",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Gps__Request, has_period),
    offsetof(Gps__Request, period),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps__request__field_indices_by_name[] = {
  0,   /* field[0] = mode */
  1,   /* field[1] = period */
};
static const ProtobufCIntRange gps__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor gps__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gps.Request",
  "Request",
  "Gps__Request",
  "gps",
  sizeof(Gps__Request),
  2,
  gps__request__field_descriptors,
  gps__request__field_indices_by_name,
  1,  gps__request__number_ranges,
  (ProtobufCMessageInit) gps__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor gps__position__field_descriptors[4] =
{
  {
    "longitude",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Gps__Position, longitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "latitude",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(Gps__Position, latitude),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Gps__Position, has_height),
    offsetof(Gps__Position, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "velocity",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(Gps__Position, has_velocity),
    offsetof(Gps__Position, velocity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned gps__position__field_indices_by_name[] = {
  2,   /* field[2] = height */
  1,   /* field[1] = latitude */
  0,   /* field[0] = longitude */
  3,   /* field[3] = velocity */
};
static const ProtobufCIntRange gps__position__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor gps__position__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "gps.Position",
  "Position",
  "Gps__Position",
  "gps",
  sizeof(Gps__Position),
  4,
  gps__position__field_descriptors,
  gps__position__field_indices_by_name,
  1,  gps__position__number_ranges,
  (ProtobufCMessageInit) gps__position__init,
  NULL,NULL,NULL    /* reserved[123] */
};
