/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: locate.proto */

#ifndef PROTOBUF_C_locate_2eproto__INCLUDED
#define PROTOBUF_C_locate_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Locate__LocateBuddy Locate__LocateBuddy;


/* --- enums --- */

typedef enum _Locate__LocateBuddy__Mode {
  LOCATE__LOCATE_BUDDY__MODE__SHAKING = 1,
  LOCATE__LOCATE_BUDDY__MODE__RINGING = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(LOCATE__LOCATE_BUDDY__MODE)
} Locate__LocateBuddy__Mode;

/* --- messages --- */

struct  _Locate__LocateBuddy
{
  ProtobufCMessage base;
  uint32_t mode;
};
#define LOCATE__LOCATE_BUDDY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&locate__locate_buddy__descriptor) \
    , 0 }


/* Locate__LocateBuddy methods */
void   locate__locate_buddy__init
                     (Locate__LocateBuddy         *message);
size_t locate__locate_buddy__get_packed_size
                     (const Locate__LocateBuddy   *message);
size_t locate__locate_buddy__pack
                     (const Locate__LocateBuddy   *message,
                      uint8_t             *out);
size_t locate__locate_buddy__pack_to_buffer
                     (const Locate__LocateBuddy   *message,
                      ProtobufCBuffer     *buffer);
Locate__LocateBuddy *
       locate__locate_buddy__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   locate__locate_buddy__free_unpacked
                     (Locate__LocateBuddy *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Locate__LocateBuddy_Closure)
                 (const Locate__LocateBuddy *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor locate__locate_buddy__descriptor;
extern const ProtobufCEnumDescriptor    locate__locate_buddy__mode__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_locate_2eproto__INCLUDED */
