/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ota.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ota.pb-c.h"
void   ota__file__init
                     (Ota__File         *message)
{
  static const Ota__File init_value = OTA__FILE__INIT;
  *message = init_value;
}
size_t ota__file__get_packed_size
                     (const Ota__File *message)
{
  assert(message->base.descriptor == &ota__file__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota__file__pack
                     (const Ota__File *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota__file__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota__file__pack_to_buffer
                     (const Ota__File *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota__file__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ota__File *
       ota__file__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ota__File *)
     protobuf_c_message_unpack (&ota__file__descriptor,
                                allocator, len, data);
}
void   ota__file__free_unpacked
                     (Ota__File *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ota__file__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota__file_request__init
                     (Ota__FileRequest         *message)
{
  static const Ota__FileRequest init_value = OTA__FILE_REQUEST__INIT;
  *message = init_value;
}
size_t ota__file_request__get_packed_size
                     (const Ota__FileRequest *message)
{
  assert(message->base.descriptor == &ota__file_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota__file_request__pack
                     (const Ota__FileRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota__file_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota__file_request__pack_to_buffer
                     (const Ota__FileRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota__file_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ota__FileRequest *
       ota__file_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ota__FileRequest *)
     protobuf_c_message_unpack (&ota__file_request__descriptor,
                                allocator, len, data);
}
void   ota__file_request__free_unpacked
                     (Ota__FileRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ota__file_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ota__file_check__init
                     (Ota__FileCheck         *message)
{
  static const Ota__FileCheck init_value = OTA__FILE_CHECK__INIT;
  *message = init_value;
}
size_t ota__file_check__get_packed_size
                     (const Ota__FileCheck *message)
{
  assert(message->base.descriptor == &ota__file_check__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ota__file_check__pack
                     (const Ota__FileCheck *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ota__file_check__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ota__file_check__pack_to_buffer
                     (const Ota__FileCheck *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ota__file_check__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ota__FileCheck *
       ota__file_check__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ota__FileCheck *)
     protobuf_c_message_unpack (&ota__file_check__descriptor,
                                allocator, len, data);
}
void   ota__file_check__free_unpacked
                     (Ota__FileCheck *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &ota__file_check__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ota__file__field_descriptors[4] =
{
  {
    "maxno",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ota__File, maxno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "no",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ota__File, no),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "crc",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FIXED32,
    offsetof(Ota__File, field_case),
    offsetof(Ota__File, crc),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ota__File, field_case),
    offsetof(Ota__File, data),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota__file__field_indices_by_name[] = {
  2,   /* field[2] = crc */
  3,   /* field[3] = data */
  0,   /* field[0] = maxno */
  1,   /* field[1] = no */
};
static const ProtobufCIntRange ota__file__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 2 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ota__file__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota.File",
  "File",
  "Ota__File",
  "ota",
  sizeof(Ota__File),
  4,
  ota__file__field_descriptors,
  ota__file__field_indices_by_name,
  2,  ota__file__number_ranges,
  (ProtobufCMessageInit) ota__file__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota__file_request__field_descriptors[2] =
{
  {
    "fmax_size",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ota__FileRequest, fmax_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "battery",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ota__FileRequest, battery),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota__file_request__field_indices_by_name[] = {
  1,   /* field[1] = battery */
  0,   /* field[0] = fmax_size */
};
static const ProtobufCIntRange ota__file_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ota__file_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota.FileRequest",
  "FileRequest",
  "Ota__FileRequest",
  "ota",
  sizeof(Ota__FileRequest),
  2,
  ota__file_request__field_descriptors,
  ota__file_request__field_indices_by_name,
  1,  ota__file_request__number_ranges,
  (ProtobufCMessageInit) ota__file_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ota__file_check__field_descriptors[1] =
{
  {
    "crc",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Ota__FileCheck, crc),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ota__file_check__field_indices_by_name[] = {
  0,   /* field[0] = crc */
};
static const ProtobufCIntRange ota__file_check__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ota__file_check__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ota.FileCheck",
  "FileCheck",
  "Ota__FileCheck",
  "ota",
  sizeof(Ota__FileCheck),
  1,
  ota__file_check__field_descriptors,
  ota__file_check__field_indices_by_name,
  1,  ota__file_check__number_ranges,
  (ProtobufCMessageInit) ota__file_check__init,
  NULL,NULL,NULL    /* reserved[123] */
};
