/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: remind.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "remind.pb-c.h"
void   remind__message__init
                     (Remind__Message         *message)
{
  static const Remind__Message init_value = REMIND__MESSAGE__INIT;
  *message = init_value;
}
size_t remind__message__get_packed_size
                     (const Remind__Message *message)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remind__message__pack
                     (const Remind__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remind__message__pack_to_buffer
                     (const Remind__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remind__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Remind__Message *
       remind__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Remind__Message *)
     protobuf_c_message_unpack (&remind__message__descriptor,
                                allocator, len, data);
}
void   remind__message__free_unpacked
                     (Remind__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remind__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   remind__battery__init
                     (Remind__Battery         *message)
{
  static const Remind__Battery init_value = REMIND__BATTERY__INIT;
  *message = init_value;
}
size_t remind__battery__get_packed_size
                     (const Remind__Battery *message)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t remind__battery__pack
                     (const Remind__Battery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t remind__battery__pack_to_buffer
                     (const Remind__Battery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &remind__battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Remind__Battery *
       remind__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Remind__Battery *)
     protobuf_c_message_unpack (&remind__battery__descriptor,
                                allocator, len, data);
}
void   remind__battery__free_unpacked
                     (Remind__Battery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &remind__battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue remind__message__type__enum_values_by_number[9] =
{
  { "TEXT", "REMIND__MESSAGE__TYPE__TEXT", 0 },
  { "FACEBOOK", "REMIND__MESSAGE__TYPE__FACEBOOK", 1 },
  { "WECHAT", "REMIND__MESSAGE__TYPE__WECHAT", 2 },
  { "QQ", "REMIND__MESSAGE__TYPE__QQ", 3 },
  { "WHATSAPP", "REMIND__MESSAGE__TYPE__WHATSAPP", 4 },
  { "MESSENGER", "REMIND__MESSAGE__TYPE__MESSENGER", 5 },
  { "TWITTER", "REMIND__MESSAGE__TYPE__TWITTER", 6 },
  { "LINKEDIN", "REMIND__MESSAGE__TYPE__LINKEDIN", 7 },
  { "INSTAGRAM", "REMIND__MESSAGE__TYPE__INSTAGRAM", 8 },
};
static const ProtobufCIntRange remind__message__type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex remind__message__type__enum_values_by_name[9] =
{
  { "FACEBOOK", 1 },
  { "INSTAGRAM", 8 },
  { "LINKEDIN", 7 },
  { "MESSENGER", 5 },
  { "QQ", 3 },
  { "TEXT", 0 },
  { "TWITTER", 6 },
  { "WECHAT", 2 },
  { "WHATSAPP", 4 },
};
const ProtobufCEnumDescriptor remind__message__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "remind.Message.Type",
  "Type",
  "Remind__Message__Type",
  "remind",
  9,
  remind__message__type__enum_values_by_number,
  9,
  remind__message__type__enum_values_by_name,
  1,
  remind__message__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Remind__Message__Type remind__message__type__default_value = REMIND__MESSAGE__TYPE__TEXT;
static const ProtobufCFieldDescriptor remind__message__field_descriptors[7] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, timestamp),
    &proto__time__unix_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, type),
    &remind__message__type__descriptor,
    &remind__message__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "maxno",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, maxno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "curno",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, curno),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "chat",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, chat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "user",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, user),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "phone",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Remind__Message, phone),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remind__message__field_indices_by_name[] = {
  4,   /* field[4] = chat */
  3,   /* field[3] = curno */
  2,   /* field[2] = maxno */
  6,   /* field[6] = phone */
  0,   /* field[0] = timestamp */
  1,   /* field[1] = type */
  5,   /* field[5] = user */
};
static const ProtobufCIntRange remind__message__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 6, 4 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor remind__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remind.Message",
  "Message",
  "Remind__Message",
  "remind",
  sizeof(Remind__Message),
  7,
  remind__message__field_descriptors,
  remind__message__field_indices_by_name,
  2,  remind__message__number_ranges,
  (ProtobufCMessageInit) remind__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor remind__battery__field_descriptors[1] =
{
  {
    "percent",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Remind__Battery, percent),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned remind__battery__field_indices_by_name[] = {
  0,   /* field[0] = percent */
};
static const ProtobufCIntRange remind__battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor remind__battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "remind.Battery",
  "Battery",
  "Remind__Battery",
  "remind",
  sizeof(Remind__Battery),
  1,
  remind__battery__field_descriptors,
  remind__battery__field_indices_by_name,
  1,  remind__battery__number_ranges,
  (ProtobufCMessageInit) remind__battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
