/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: transfer.proto */

#ifndef PROTOBUF_C_transfer_2eproto__INCLUDED
#define PROTOBUF_C_transfer_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Transfer__Packet Transfer__Packet;


/* --- enums --- */


/* --- messages --- */

struct  _Transfer__Packet
{
  ProtobufCMessage base;
  protobuf_c_boolean has_next;
};
#define TRANSFER__PACKET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&transfer__packet__descriptor) \
    , 0 }


/* Transfer__Packet methods */
void   transfer__packet__init
                     (Transfer__Packet         *message);
size_t transfer__packet__get_packed_size
                     (const Transfer__Packet   *message);
size_t transfer__packet__pack
                     (const Transfer__Packet   *message,
                      uint8_t             *out);
size_t transfer__packet__pack_to_buffer
                     (const Transfer__Packet   *message,
                      ProtobufCBuffer     *buffer);
Transfer__Packet *
       transfer__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   transfer__packet__free_unpacked
                     (Transfer__Packet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Transfer__Packet_Closure)
                 (const Transfer__Packet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor transfer__packet__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_transfer_2eproto__INCLUDED */
