/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: userinfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "userinfo.pb-c.h"
void   user__user_information__init
                     (User__UserInformation         *message)
{
  static const User__UserInformation init_value = USER__USER_INFORMATION__INIT;
  *message = init_value;
}
size_t user__user_information__get_packed_size
                     (const User__UserInformation *message)
{
  assert(message->base.descriptor == &user__user_information__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t user__user_information__pack
                     (const User__UserInformation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &user__user_information__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t user__user_information__pack_to_buffer
                     (const User__UserInformation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &user__user_information__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
User__UserInformation *
       user__user_information__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (User__UserInformation *)
     protobuf_c_message_unpack (&user__user_information__descriptor,
                                allocator, len, data);
}
void   user__user_information__free_unpacked
                     (User__UserInformation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &user__user_information__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor user__user_information__field_descriptors[4] =
{
  {
    "age",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User__UserInformation, age),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User__UserInformation, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "weight",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User__UserInformation, weight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sex",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(User__UserInformation, sex),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned user__user_information__field_indices_by_name[] = {
  0,   /* field[0] = age */
  1,   /* field[1] = height */
  3,   /* field[3] = sex */
  2,   /* field[2] = weight */
};
static const ProtobufCIntRange user__user_information__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor user__user_information__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "user.UserInformation",
  "UserInformation",
  "User__UserInformation",
  "user",
  sizeof(User__UserInformation),
  4,
  user__user_information__field_descriptors,
  user__user_information__field_indices_by_name,
  1,  user__user_information__number_ranges,
  (ProtobufCMessageInit) user__user_information__init,
  NULL,NULL,NULL    /* reserved[123] */
};
