/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: weather.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "weather.pb-c.h"
void   weather__base__init
                     (Weather__Base         *message)
{
  static const Weather__Base init_value = WEATHER__BASE__INIT;
  *message = init_value;
}
size_t weather__base__get_packed_size
                     (const Weather__Base *message)
{
  assert(message->base.descriptor == &weather__base__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t weather__base__pack
                     (const Weather__Base *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &weather__base__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t weather__base__pack_to_buffer
                     (const Weather__Base *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &weather__base__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Weather__Base *
       weather__base__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Weather__Base *)
     protobuf_c_message_unpack (&weather__base__descriptor,
                                allocator, len, data);
}
void   weather__base__free_unpacked
                     (Weather__Base *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &weather__base__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   weather__ultraviolet__init
                     (Weather__Ultraviolet         *message)
{
  static const Weather__Ultraviolet init_value = WEATHER__ULTRAVIOLET__INIT;
  *message = init_value;
}
size_t weather__ultraviolet__get_packed_size
                     (const Weather__Ultraviolet *message)
{
  assert(message->base.descriptor == &weather__ultraviolet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t weather__ultraviolet__pack
                     (const Weather__Ultraviolet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &weather__ultraviolet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t weather__ultraviolet__pack_to_buffer
                     (const Weather__Ultraviolet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &weather__ultraviolet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Weather__Ultraviolet *
       weather__ultraviolet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Weather__Ultraviolet *)
     protobuf_c_message_unpack (&weather__ultraviolet__descriptor,
                                allocator, len, data);
}
void   weather__ultraviolet__free_unpacked
                     (Weather__Ultraviolet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &weather__ultraviolet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue weather__base__weather__enum_values_by_number[4] =
{
  { "SUNNY", "WEATHER__BASE__WEATHER__SUNNY", 0 },
  { "CLOUDY", "WEATHER__BASE__WEATHER__CLOUDY", 1 },
  { "RAINY", "WEATHER__BASE__WEATHER__RAINY", 2 },
  { "SNOWY", "WEATHER__BASE__WEATHER__SNOWY", 3 },
};
static const ProtobufCIntRange weather__base__weather__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex weather__base__weather__enum_values_by_name[4] =
{
  { "CLOUDY", 1 },
  { "RAINY", 2 },
  { "SNOWY", 3 },
  { "SUNNY", 0 },
};
const ProtobufCEnumDescriptor weather__base__weather__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "weather.Base.Weather",
  "Weather",
  "Weather__Base__Weather",
  "weather",
  4,
  weather__base__weather__enum_values_by_number,
  4,
  weather__base__weather__enum_values_by_name,
  1,
  weather__base__weather__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Weather__Base__Weather weather__base__howday__default_value = WEATHER__BASE__WEATHER__SUNNY;
static const ProtobufCFieldDescriptor weather__base__field_descriptors[3] =
{
  {
    "temp_low",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Weather__Base, temp_low),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "temp_high",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Weather__Base, temp_high),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "howday",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(Weather__Base, howday),
    &weather__base__weather__descriptor,
    &weather__base__howday__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__base__field_indices_by_name[] = {
  2,   /* field[2] = howday */
  1,   /* field[1] = temp_high */
  0,   /* field[0] = temp_low */
};
static const ProtobufCIntRange weather__base__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor weather__base__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.Base",
  "Base",
  "Weather__Base",
  "weather",
  sizeof(Weather__Base),
  3,
  weather__base__field_descriptors,
  weather__base__field_indices_by_name,
  1,  weather__base__number_ranges,
  (ProtobufCMessageInit) weather__base__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue weather__ultraviolet__level__enum_values_by_number[3] =
{
  { "LOW", "WEATHER__ULTRAVIOLET__LEVEL__LOW", 0 },
  { "MIDDLE", "WEATHER__ULTRAVIOLET__LEVEL__MIDDLE", 1 },
  { "HIGH", "WEATHER__ULTRAVIOLET__LEVEL__HIGH", 2 },
};
static const ProtobufCIntRange weather__ultraviolet__level__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex weather__ultraviolet__level__enum_values_by_name[3] =
{
  { "HIGH", 2 },
  { "LOW", 0 },
  { "MIDDLE", 1 },
};
const ProtobufCEnumDescriptor weather__ultraviolet__level__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "weather.Ultraviolet.Level",
  "Level",
  "Weather__Ultraviolet__Level",
  "weather",
  3,
  weather__ultraviolet__level__enum_values_by_number,
  3,
  weather__ultraviolet__level__enum_values_by_name,
  1,
  weather__ultraviolet__level__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor weather__ultraviolet__field_descriptors[2] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Weather__Ultraviolet, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "timestamp",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Weather__Ultraviolet, timestamp),
    &proto__time__unix_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned weather__ultraviolet__field_indices_by_name[] = {
  0,   /* field[0] = level */
  1,   /* field[1] = timestamp */
};
static const ProtobufCIntRange weather__ultraviolet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor weather__ultraviolet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "weather.Ultraviolet",
  "Ultraviolet",
  "Weather__Ultraviolet",
  "weather",
  sizeof(Weather__Ultraviolet),
  2,
  weather__ultraviolet__field_descriptors,
  weather__ultraviolet__field_indices_by_name,
  1,  weather__ultraviolet__number_ranges,
  (ProtobufCMessageInit) weather__ultraviolet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
