/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0                                               */
/*  Date (dd.mm.yyyy): 20. 1.2021   Time (hh:mm): 08:57                        */
/*******************************************************************************/


#ifndef _GUIX_SIMPLE_MAIN_DISPLAY_RESOURCES_H_
#define _GUIX_SIMPLE_MAIN_DISPLAY_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define MAIN_DISPLAY 0
#define MAIN_DISPLAY_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define MAIN_DISPLAY_X_RESOLUTION 360
#define MAIN_DISPLAY_Y_RESOLUTION 360
#define MAIN_DISPLAY_THEME_1 0
#define MAIN_DISPLAY_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define MAIN_DISPLAY_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_BLUE 29
#define MAIN_DISPLAY_COLOR_TABLE_SIZE 30

/* Font ID definitions                                                         */

#define MAIN_DISPLAY_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define GX_PIXELMAP_ID_BATTERY 5
#define GX_PIXELMAP_ID_BLUETOOTH 6
#define GX_PIXELMAP_ID_SOUND 7
#define GX_PIXELMAP_ID_WIFI 8
#define MAIN_DISPLAY_PIXELMAP_TABLE_SIZE 9

/* String Ids                                                                  */

#define GX_STRING_ID_STRING_1 1
#define GX_STRING_ID_STRING_2 2
#define GX_STRING_ID_STRING_3 3
#define MAIN_DISPLAY_STRING_TABLE_SIZE 4

#endif                                       /* sentry                         */
