/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: devinfo.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "devinfo.pb-c.h"
void   info__device__init
                     (Info__Device         *message)
{
  static const Info__Device init_value = INFO__DEVICE__INIT;
  *message = init_value;
}
size_t info__device__get_packed_size
                     (const Info__Device *message)
{
  assert(message->base.descriptor == &info__device__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__device__pack
                     (const Info__Device *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__device__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__device__pack_to_buffer
                     (const Info__Device *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__device__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info__Device *
       info__device__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info__Device *)
     protobuf_c_message_unpack (&info__device__descriptor,
                                allocator, len, data);
}
void   info__device__free_unpacked
                     (Info__Device *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &info__device__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   info__battery__init
                     (Info__Battery         *message)
{
  static const Info__Battery init_value = INFO__BATTERY__INIT;
  *message = init_value;
}
size_t info__battery__get_packed_size
                     (const Info__Battery *message)
{
  assert(message->base.descriptor == &info__battery__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t info__battery__pack
                     (const Info__Battery *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &info__battery__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t info__battery__pack_to_buffer
                     (const Info__Battery *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &info__battery__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Info__Battery *
       info__battery__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Info__Battery *)
     protobuf_c_message_unpack (&info__battery__descriptor,
                                allocator, len, data);
}
void   info__battery__free_unpacked
                     (Info__Battery *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &info__battery__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue info__device__type__enum_values_by_number[4] =
{
  { "INVALID", "INFO__DEVICE__TYPE__INVALID", 0 },
  { "BAND", "INFO__DEVICE__TYPE__BAND", 1 },
  { "WATCH", "INFO__DEVICE__TYPE__WATCH", 2 },
  { "EARPHONES", "INFO__DEVICE__TYPE__EARPHONES", 3 },
};
static const ProtobufCIntRange info__device__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex info__device__type__enum_values_by_name[4] =
{
  { "BAND", 1 },
  { "EARPHONES", 3 },
  { "INVALID", 0 },
  { "WATCH", 2 },
};
const ProtobufCEnumDescriptor info__device__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "info.Device.Type",
  "Type",
  "Info__Device__Type",
  "info",
  4,
  info__device__type__enum_values_by_number,
  4,
  info__device__type__enum_values_by_name,
  1,
  info__device__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue info__device__model__enum_values_by_number[2] =
{
  { "DM_INVALID", "INFO__DEVICE__MODEL__DM_INVALID", 0 },
  { "DM_APOLLO3P", "INFO__DEVICE__MODEL__DM_APOLLO3P", 1 },
};
static const ProtobufCIntRange info__device__model__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex info__device__model__enum_values_by_name[2] =
{
  { "DM_APOLLO3P", 1 },
  { "DM_INVALID", 0 },
};
const ProtobufCEnumDescriptor info__device__model__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "info.Device.Model",
  "Model",
  "Info__Device__Model",
  "info",
  2,
  info__device__model__enum_values_by_number,
  2,
  info__device__model__enum_values_by_name,
  1,
  info__device__model__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const Info__Device__Type info__device__type__default_value = INFO__DEVICE__TYPE__INVALID;
static const Info__Device__Model info__device__model__default_value = INFO__DEVICE__MODEL__DM_INVALID;
static const ProtobufCFieldDescriptor info__device__field_descriptors[6] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Info__Device, has_type),
    offsetof(Info__Device, type),
    &info__device__type__descriptor,
    &info__device__type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "model",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Info__Device, has_model),
    offsetof(Info__Device, model),
    &info__device__model__descriptor,
    &info__device__model__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firmware_ver",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Info__Device, has_firmware_ver),
    offsetof(Info__Device, firmware_ver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hardware_ver",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Info__Device, has_hardware_ver),
    offsetof(Info__Device, hardware_ver),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sn",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Info__Device, has_sn),
    offsetof(Info__Device, sn),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mac",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Info__Device, has_mac),
    offsetof(Info__Device, mac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__device__field_indices_by_name[] = {
  2,   /* field[2] = firmware_ver */
  3,   /* field[3] = hardware_ver */
  5,   /* field[5] = mac */
  1,   /* field[1] = model */
  4,   /* field[4] = sn */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange info__device__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 7, 4 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor info__device__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "info.Device",
  "Device",
  "Info__Device",
  "info",
  sizeof(Info__Device),
  6,
  info__device__field_descriptors,
  info__device__field_indices_by_name,
  2,  info__device__number_ranges,
  (ProtobufCMessageInit) info__device__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue info__battery__status__enum_values_by_number[3] =
{
  { "IDLE", "INFO__BATTERY__STATUS__IDLE", 0 },
  { "CHARGING", "INFO__BATTERY__STATUS__CHARGING", 1 },
  { "CHARGE_COMPLETED", "INFO__BATTERY__STATUS__CHARGE_COMPLETED", 2 },
};
static const ProtobufCIntRange info__battery__status__value_ranges[] = {
{0, 0},{0, 3}
};
static const ProtobufCEnumValueIndex info__battery__status__enum_values_by_name[3] =
{
  { "CHARGE_COMPLETED", 2 },
  { "CHARGING", 1 },
  { "IDLE", 0 },
};
const ProtobufCEnumDescriptor info__battery__status__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "info.Battery.Status",
  "Status",
  "Info__Battery__Status",
  "info",
  3,
  info__battery__status__enum_values_by_number,
  3,
  info__battery__status__enum_values_by_name,
  1,
  info__battery__status__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor info__battery__field_descriptors[2] =
{
  {
    "level",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Info__Battery, level),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Info__Battery, has_status),
    offsetof(Info__Battery, status),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned info__battery__field_indices_by_name[] = {
  0,   /* field[0] = level */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange info__battery__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor info__battery__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "info.Battery",
  "Battery",
  "Info__Battery",
  "info",
  sizeof(Info__Battery),
  2,
  info__battery__field_descriptors,
  info__battery__field_indices_by_name,
  1,  info__battery__number_ranges,
  (ProtobufCMessageInit) info__battery__init,
  NULL,NULL,NULL    /* reserved[123] */
};
