/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gps.proto */

#ifndef PROTOBUF_C_gps_2eproto__INCLUDED
#define PROTOBUF_C_gps_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Gps__Request Gps__Request;
typedef struct _Gps__Position Gps__Position;


/* --- enums --- */

typedef enum _Gps__Request__StartMode {
  GPS__REQUEST__START_MODE__ONESHOT = 0,
  GPS__REQUEST__START_MODE__PERIOD = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GPS__REQUEST__START_MODE)
} Gps__Request__StartMode;

/* --- messages --- */

struct  _Gps__Request
{
  ProtobufCMessage base;
  Gps__Request__StartMode mode;
  /*
   *[unit: seconds]
   */
  protobuf_c_boolean has_period;
  uint32_t period;
};
#define GPS__REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gps__request__descriptor) \
    , GPS__REQUEST__START_MODE__ONESHOT, 0, 0 }


struct  _Gps__Position
{
  ProtobufCMessage base;
  float longitude;
  float latitude;
  protobuf_c_boolean has_height;
  float height;
  protobuf_c_boolean has_velocity;
  float velocity;
};
#define GPS__POSITION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gps__position__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


/* Gps__Request methods */
void   gps__request__init
                     (Gps__Request         *message);
size_t gps__request__get_packed_size
                     (const Gps__Request   *message);
size_t gps__request__pack
                     (const Gps__Request   *message,
                      uint8_t             *out);
size_t gps__request__pack_to_buffer
                     (const Gps__Request   *message,
                      ProtobufCBuffer     *buffer);
Gps__Request *
       gps__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gps__request__free_unpacked
                     (Gps__Request *message,
                      ProtobufCAllocator *allocator);
/* Gps__Position methods */
void   gps__position__init
                     (Gps__Position         *message);
size_t gps__position__get_packed_size
                     (const Gps__Position   *message);
size_t gps__position__pack
                     (const Gps__Position   *message,
                      uint8_t             *out);
size_t gps__position__pack_to_buffer
                     (const Gps__Position   *message,
                      ProtobufCBuffer     *buffer);
Gps__Position *
       gps__position__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gps__position__free_unpacked
                     (Gps__Position *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Gps__Request_Closure)
                 (const Gps__Request *message,
                  void *closure_data);
typedef void (*Gps__Position_Closure)
                 (const Gps__Position *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor gps__request__descriptor;
extern const ProtobufCEnumDescriptor    gps__request__start_mode__descriptor;
extern const ProtobufCMessageDescriptor gps__position__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_gps_2eproto__INCLUDED */
