/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: music.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "music.pb-c.h"
void   music__player__init
                     (Music__Player         *message)
{
  static const Music__Player init_value = MUSIC__PLAYER__INIT;
  *message = init_value;
}
size_t music__player__get_packed_size
                     (const Music__Player *message)
{
  assert(message->base.descriptor == &music__player__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t music__player__pack
                     (const Music__Player *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &music__player__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t music__player__pack_to_buffer
                     (const Music__Player *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &music__player__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Music__Player *
       music__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Music__Player *)
     protobuf_c_message_unpack (&music__player__descriptor,
                                allocator, len, data);
}
void   music__player__free_unpacked
                     (Music__Player *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &music__player__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor music__player__field_descriptors[2] =
{
  {
    "song",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Music__Player, song),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "volume",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Music__Player, has_volume),
    offsetof(Music__Player, volume),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned music__player__field_indices_by_name[] = {
  0,   /* field[0] = song */
  1,   /* field[1] = volume */
};
static const ProtobufCIntRange music__player__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor music__player__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "music.Player",
  "Player",
  "Music__Player",
  "music",
  sizeof(Music__Player),
  2,
  music__player__field_descriptors,
  music__player__field_indices_by_name,
  1,  music__player__number_ranges,
  (ProtobufCMessageInit) music__player__init,
  NULL,NULL,NULL    /* reserved[123] */
};
