/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: music.proto */

#ifndef PROTOBUF_C_music_2eproto__INCLUDED
#define PROTOBUF_C_music_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _Music__Player Music__Player;


/* --- enums --- */


/* --- messages --- */

struct  _Music__Player
{
  ProtobufCMessage base;
  char *song;
  /*
   * range[0, 100]
   */
  protobuf_c_boolean has_volume;
  uint32_t volume;
};
#define MUSIC__PLAYER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&music__player__descriptor) \
    , NULL, 0, 0 }


/* Music__Player methods */
void   music__player__init
                     (Music__Player         *message);
size_t music__player__get_packed_size
                     (const Music__Player   *message);
size_t music__player__pack
                     (const Music__Player   *message,
                      uint8_t             *out);
size_t music__player__pack_to_buffer
                     (const Music__Player   *message,
                      ProtobufCBuffer     *buffer);
Music__Player *
       music__player__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   music__player__free_unpacked
                     (Music__Player *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Music__Player_Closure)
                 (const Music__Player *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor music__player__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_music_2eproto__INCLUDED */
