/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: time.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "time.pb-c.h"
void   proto__time__unix_timestamp__init
                     (Proto__Time__UnixTimestamp         *message)
{
  static const Proto__Time__UnixTimestamp init_value = PROTO__TIME__UNIX_TIMESTAMP__INIT;
  *message = init_value;
}
size_t proto__time__unix_timestamp__get_packed_size
                     (const Proto__Time__UnixTimestamp *message)
{
  assert(message->base.descriptor == &proto__time__unix_timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t proto__time__unix_timestamp__pack
                     (const Proto__Time__UnixTimestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &proto__time__unix_timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t proto__time__unix_timestamp__pack_to_buffer
                     (const Proto__Time__UnixTimestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &proto__time__unix_timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Proto__Time__UnixTimestamp *
       proto__time__unix_timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Proto__Time__UnixTimestamp *)
     protobuf_c_message_unpack (&proto__time__unix_timestamp__descriptor,
                                allocator, len, data);
}
void   proto__time__unix_timestamp__free_unpacked
                     (Proto__Time__UnixTimestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &proto__time__unix_timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor proto__time__unix_timestamp__field_descriptors[1] =
{
  {
    "time",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FIXED32,
    0,   /* quantifier_offset */
    offsetof(Proto__Time__UnixTimestamp, time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned proto__time__unix_timestamp__field_indices_by_name[] = {
  0,   /* field[0] = time */
};
static const ProtobufCIntRange proto__time__unix_timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor proto__time__unix_timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "proto.time.UnixTimestamp",
  "UnixTimestamp",
  "Proto__Time__UnixTimestamp",
  "proto.time",
  sizeof(Proto__Time__UnixTimestamp),
  1,
  proto__time__unix_timestamp__field_descriptors,
  proto__time__unix_timestamp__field_indices_by_name,
  1,  proto__time__unix_timestamp__number_ranges,
  (ProtobufCMessageInit) proto__time__unix_timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
