/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: transfer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "transfer.pb-c.h"
void   transfer__packet__init
                     (Transfer__Packet         *message)
{
  static const Transfer__Packet init_value = TRANSFER__PACKET__INIT;
  *message = init_value;
}
size_t transfer__packet__get_packed_size
                     (const Transfer__Packet *message)
{
  assert(message->base.descriptor == &transfer__packet__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t transfer__packet__pack
                     (const Transfer__Packet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &transfer__packet__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t transfer__packet__pack_to_buffer
                     (const Transfer__Packet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &transfer__packet__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Transfer__Packet *
       transfer__packet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Transfer__Packet *)
     protobuf_c_message_unpack (&transfer__packet__descriptor,
                                allocator, len, data);
}
void   transfer__packet__free_unpacked
                     (Transfer__Packet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &transfer__packet__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor transfer__packet__field_descriptors[1] =
{
  {
    "has_next",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Transfer__Packet, has_next),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned transfer__packet__field_indices_by_name[] = {
  0,   /* field[0] = has_next */
};
static const ProtobufCIntRange transfer__packet__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor transfer__packet__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "transfer.Packet",
  "Packet",
  "Transfer__Packet",
  "transfer",
  sizeof(Transfer__Packet),
  1,
  transfer__packet__field_descriptors,
  transfer__packet__field_indices_by_name,
  1,  transfer__packet__number_ranges,
  (ProtobufCMessageInit) transfer__packet__init,
  NULL,NULL,NULL    /* reserved[123] */
};
