/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: weather.proto */

#ifndef PROTOBUF_C_weather_2eproto__INCLUDED
#define PROTOBUF_C_weather_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "time.pb-c.h"

typedef struct _Weather__Base Weather__Base;
typedef struct _Weather__Ultraviolet Weather__Ultraviolet;


/* --- enums --- */

typedef enum _Weather__Base__Weather {
  WEATHER__BASE__WEATHER__SUNNY = 0,
  WEATHER__BASE__WEATHER__CLOUDY = 1,
  WEATHER__BASE__WEATHER__RAINY = 2,
  WEATHER__BASE__WEATHER__SNOWY = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WEATHER__BASE__WEATHER)
} Weather__Base__Weather;
typedef enum _Weather__Ultraviolet__Level {
  WEATHER__ULTRAVIOLET__LEVEL__LOW = 0,
  WEATHER__ULTRAVIOLET__LEVEL__MIDDLE = 1,
  WEATHER__ULTRAVIOLET__LEVEL__HIGH = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WEATHER__ULTRAVIOLET__LEVEL)
} Weather__Ultraviolet__Level;

/* --- messages --- */

struct  _Weather__Base
{
  ProtobufCMessage base;
  uint32_t temp_low;
  uint32_t temp_high;
  Weather__Base__Weather howday;
};
#define WEATHER__BASE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&weather__base__descriptor) \
    , 0, 0, WEATHER__BASE__WEATHER__SUNNY }


struct  _Weather__Ultraviolet
{
  ProtobufCMessage base;
  uint32_t level;
  Proto__Time__UnixTimestamp *timestamp;
};
#define WEATHER__ULTRAVIOLET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&weather__ultraviolet__descriptor) \
    , 0, NULL }


/* Weather__Base methods */
void   weather__base__init
                     (Weather__Base         *message);
size_t weather__base__get_packed_size
                     (const Weather__Base   *message);
size_t weather__base__pack
                     (const Weather__Base   *message,
                      uint8_t             *out);
size_t weather__base__pack_to_buffer
                     (const Weather__Base   *message,
                      ProtobufCBuffer     *buffer);
Weather__Base *
       weather__base__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   weather__base__free_unpacked
                     (Weather__Base *message,
                      ProtobufCAllocator *allocator);
/* Weather__Ultraviolet methods */
void   weather__ultraviolet__init
                     (Weather__Ultraviolet         *message);
size_t weather__ultraviolet__get_packed_size
                     (const Weather__Ultraviolet   *message);
size_t weather__ultraviolet__pack
                     (const Weather__Ultraviolet   *message,
                      uint8_t             *out);
size_t weather__ultraviolet__pack_to_buffer
                     (const Weather__Ultraviolet   *message,
                      ProtobufCBuffer     *buffer);
Weather__Ultraviolet *
       weather__ultraviolet__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   weather__ultraviolet__free_unpacked
                     (Weather__Ultraviolet *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Weather__Base_Closure)
                 (const Weather__Base *message,
                  void *closure_data);
typedef void (*Weather__Ultraviolet_Closure)
                 (const Weather__Ultraviolet *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor weather__base__descriptor;
extern const ProtobufCEnumDescriptor    weather__base__weather__descriptor;
extern const ProtobufCMessageDescriptor weather__ultraviolet__descriptor;
extern const ProtobufCEnumDescriptor    weather__ultraviolet__level__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_weather_2eproto__INCLUDED */
