/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this */
/*  file by hand. Modifications to this file should only be made by running */
/*  the Azure RTOS GUIX Studio application and re-generating the application */
/*  specification file(s). For more information please refer to the Azure RTOS
 */
/*  GUIX Studio User Guide, or visit our web site at azure.com/rtos */
/*                                                                             */
/*  GUIX Studio Revision 6.1.0.0 */
/*  Date (dd.mm.yyyy):  3. 2.2021   Time (hh:mm): 13:46 */
/*******************************************************************************/

#define GUIX_STUDIO_GENERATED_FILE
#include "guix_simple_specifications.h"
#include "guix_simple_resources.h"
#include <stddef.h>

static GX_WIDGET *gx_studio_nested_widget_create(
	GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent);
ALARM_LIST_CONTROL_BLOCK alarm_list;
ALARM_WINDOW_CONTROL_BLOCK alarm_window;
WINDOW_2_CONTROL_BLOCK window_2;
STATUS_WINDOW_CONTROL_BLOCK status_window;
ROOT_WINDOW_CONTROL_BLOCK root_window;
WINDOW_CONTROL_BLOCK window;
GX_DISPLAY main_display_control_block;
GX_WINDOW_ROOT main_display_root_window;
GX_CANVAS main_display_canvas_control_block;
ULONG main_display_canvas_memory[64800];

extern GX_CONST GX_THEME *main_display_theme_table[];
extern GX_CONST GX_STRING *main_display_language_table[];

GX_STUDIO_DISPLAY_INFO guix_simple_display_table[1] = {{
	"main_display", "main_display_canvas", main_display_theme_table,
	main_display_language_table, MAIN_DISPLAY_THEME_TABLE_SIZE,
	MAIN_DISPLAY_LANGUAGE_TABLE_SIZE, MAIN_DISPLAY_STRING_TABLE_SIZE,
	360, /* x resolution                   */
	360, /* y resolution                   */
	&main_display_control_block, &main_display_canvas_control_block,
	&main_display_root_window,
	main_display_canvas_memory, /* canvas memory area             */
	259200						/* canvas memory size in bytes    */
}};

UINT gx_studio_pixelmap_button_create(GX_CONST GX_STUDIO_WIDGET *info,
									  GX_WIDGET *control_block,
									  GX_WIDGET *parent)
{
	UINT status;
	GX_PIXELMAP_BUTTON *button = (GX_PIXELMAP_BUTTON *)control_block;
	GX_PIXELMAP_BUTTON_PROPERTIES *props =
		(GX_PIXELMAP_BUTTON_PROPERTIES *)info->properties;
	status = gx_pixelmap_button_create(
		button, info->widget_name, parent, props->normal_pixelmap_id,
		props->selected_pixelmap_id, props->disabled_pixelmap_id, info->style,
		info->widget_id, &info->size);
	return status;
}

UINT gx_studio_icon_create(GX_CONST GX_STUDIO_WIDGET *info,
						   GX_WIDGET *control_block, GX_WIDGET *parent)
{
	UINT status;
	GX_ICON *icon = (GX_ICON *)control_block;
	GX_ICON_PROPERTIES *props = (GX_ICON_PROPERTIES *)info->properties;
	status = gx_icon_create(icon, info->widget_name, parent,
							props->normal_pixelmap_id, info->style,
							info->widget_id, info->size.gx_rectangle_left,
							info->size.gx_rectangle_top);
	if (props->selected_pixelmap_id) {
		gx_icon_pixelmap_set(icon, props->normal_pixelmap_id,
							 props->selected_pixelmap_id);
	}
	return status;
}

UINT gx_studio_prompt_create(GX_CONST GX_STUDIO_WIDGET *info,
							 GX_WIDGET *control_block, GX_WIDGET *parent)
{
	UINT status;
	GX_PROMPT *prompt = (GX_PROMPT *)control_block;
	GX_PROMPT_PROPERTIES *props = (GX_PROMPT_PROPERTIES *)info->properties;
	status =
		gx_prompt_create(prompt, info->widget_name, parent, props->string_id,
						 info->style, info->widget_id, &info->size);
	if (status == GX_SUCCESS) {
		gx_prompt_font_set(prompt, props->font_id);
#if defined(GUIX_5_4_0_COMPATIBILITY)
		gx_prompt_text_color_set(prompt, props->normal_text_color_id,
								 props->selected_text_color_id);
#else
		gx_prompt_text_color_set(prompt, props->normal_text_color_id,
								 props->selected_text_color_id,
								 props->disabled_text_color_id);
#endif
	}
	return status;
}

UINT gx_studio_window_create(GX_CONST GX_STUDIO_WIDGET *info,
							 GX_WIDGET *control_block, GX_WIDGET *parent)
{
	UINT status;
	GX_WINDOW *window = (GX_WINDOW *)control_block;
	GX_WINDOW_PROPERTIES *props = (GX_WINDOW_PROPERTIES *)info->properties;
	status = gx_window_create(window, info->widget_name, parent, info->style,
							  info->widget_id, &info->size);
	if (status == GX_SUCCESS) {
		if (props->wallpaper_id) {
			gx_window_wallpaper_set(window, props->wallpaper_id,
									info->style & GX_STYLE_TILE_WALLPAPER);
		}
	}
	return status;
}

UINT gx_studio_vertical_list_create(GX_CONST GX_STUDIO_WIDGET *info,
									GX_WIDGET *control_block, GX_WIDGET *parent)
{
	UINT status;
	GX_VERTICAL_LIST *list = (GX_VERTICAL_LIST *)control_block;
	GX_VERTICAL_LIST_PROPERTIES *props =
		(GX_VERTICAL_LIST_PROPERTIES *)info->properties;
	status = gx_vertical_list_create(list, info->widget_name, parent,
									 props->total_rows, props->callback,
									 info->style, info->widget_id, &info->size);
	if (status == GX_SUCCESS) {
		if (props->wallpaper_id) {
			gx_window_wallpaper_set((GX_WINDOW *)list, props->wallpaper_id,
									info->style & GX_STYLE_TILE_WALLPAPER);
		}
	}
	return status;
}

UINT gx_studio_vertical_scrollbar_create(GX_CONST GX_STUDIO_WIDGET *info,
										 GX_WIDGET *control_block,
										 GX_WIDGET *parent)
{
	UINT status;
	GX_SCROLLBAR *scroll = (GX_SCROLLBAR *)control_block;
	GX_SCROLLBAR_APPEARANCE *appearance =
		(GX_SCROLLBAR_APPEARANCE *)info->properties;
	status = gx_vertical_scrollbar_create(scroll, info->widget_name, parent,
										  appearance, info->style);
	return status;
}
GX_VERTICAL_LIST_PROPERTIES alarm_list_properties = {
	0,					   /* wallpaper id                   */
	alarm_list_row_create, /* callback function              */
	6					   /* total rows                     */
};
GX_SCROLLBAR_APPEARANCE alarm_list_vertical_scroll_9_properties = {
	6,				  /* scroll width                   */
	6,				  /* thumb width                    */
	0,				  /* thumb travel min               */
	0,				  /* thumb travel max               */
	4,				  /* thumb border style             */
	0,				  /* scroll fill pixelmap           */
	0,				  /* scroll thumb pixelmap          */
	0,				  /* scroll up pixelmap             */
	0,				  /* scroll down pixelmap           */
	GX_COLOR_ID_GRAY, /* scroll thumb color             */
	GX_COLOR_ID_GRAY, /* scroll thumb border color      */
	GX_COLOR_ID_GRAY, /* scroll button color            */
};

GX_CONST GX_STUDIO_WIDGET alarm_list_vertical_scroll_9_define = {
	"vertical_scroll_9",
	GX_TYPE_VERTICAL_SCROLL, /* widget type                    */
	GX_ID_NONE,				 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_SCROLLBAR_RELATIVE_THUMB |
		GX_SCROLLBAR_VERTICAL,			 /* style flags */
	0,									 /* status flags                   */
	sizeof(GX_SCROLLBAR),				 /* control block size             */
	GX_COLOR_ID_BLACK,					 /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL,			 /* selected color id              */
	GX_COLOR_ID_BLACK,					 /* disabled color id              */
	gx_studio_vertical_scrollbar_create, /* create function                */
	GX_NULL,							 /* drawing function override      */
	GX_NULL,							 /* event function override        */
	{314, 80, 319, 319},				 /* widget size                    */
	GX_NULL,							 /* no next widget                 */
	GX_NULL,							 /* no child widgets               */
	offsetof(ALARM_LIST_CONTROL_BLOCK,
			 alarm_list_vertical_scroll_9),			 /* control block */
	(void *)&alarm_list_vertical_scroll_9_properties /* extended properties   */
};

GX_CONST GX_STUDIO_WIDGET alarm_list_define = {
	"alarm_list",
	GX_TYPE_VERTICAL_LIST, /* widget type                    */
	GX_ID_NONE,			   /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,			  /* status flags                   */
	sizeof(ALARM_LIST_CONTROL_BLOCK),	  /* control block size             */
	GX_COLOR_ID_WINDOW_FILL,			  /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,			  /* selected color id              */
	GX_COLOR_ID_WINDOW_FILL,			  /* disabled color id              */
	gx_studio_vertical_list_create,		  /* create function                */
	GX_NULL,							  /* drawing function override      */
	GX_NULL,							  /* event function override        */
	{40, 80, 319, 319},					  /* widget size                    */
	GX_NULL,							  /* next widget                    */
	&alarm_list_vertical_scroll_9_define, /* child widget                   */
	0,									  /* control block                  */
	(void *)&alarm_list_properties		  /* extended properties            */
};
GX_WINDOW_PROPERTIES alarm_window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES alarm_window_window_6_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES alarm_window_alarm_add_properties = {
	GX_PIXELMAP_ID_CALCULATOR_PLUS, /* normal pixelmap id             */
	0,								/* selected pixelmap id           */
	0								/* disabled pixelmap id           */
};
GX_VERTICAL_LIST_PROPERTIES alarm_window_alarm_list_properties = {
	0,					   /* wallpaper id                   */
	alarm_list_row_create, /* callback function              */
	6					   /* total rows                     */
};
GX_SCROLLBAR_APPEARANCE alarm_window_vertical_scroll_9_properties = {
	6,				  /* scroll width                   */
	6,				  /* thumb width                    */
	0,				  /* thumb travel min               */
	0,				  /* thumb travel max               */
	4,				  /* thumb border style             */
	0,				  /* scroll fill pixelmap           */
	0,				  /* scroll thumb pixelmap          */
	0,				  /* scroll up pixelmap             */
	0,				  /* scroll down pixelmap           */
	GX_COLOR_ID_GRAY, /* scroll thumb color             */
	GX_COLOR_ID_GRAY, /* scroll thumb border color      */
	GX_COLOR_ID_GRAY, /* scroll button color            */
};

GX_CONST GX_STUDIO_WIDGET alarm_window_alarm_add_define = {
	"alarm_add",
	GX_TYPE_PIXELMAP_BUTTON, /* widget type                    */
	ID_ADD,					 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_CENTER |
		GX_STYLE_VALIGN_CENTER,		  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		  /* status flags                   */
	sizeof(GX_PIXELMAP_BUTTON),		  /* control block size             */
	GX_COLOR_ID_GRAY,				  /* normal color id                */
	GX_COLOR_ID_BLUE,				  /* selected color id              */
	GX_COLOR_ID_GRAY,				  /* disabled color id              */
	gx_studio_pixelmap_button_create, /* create function                */
	(VOID (*)(GX_WIDGET *))
		custom_pixelmap_button_draw, /* drawing function override */
	(UINT (*)(GX_WIDGET *,
			  GX_EVENT *))alarm_add_event, /* event function override */
	{0, 0, 359, 69},					   /* widget size                    */
	GX_NULL,							   /* no next widget                 */
	GX_NULL,							   /* no child widgets               */
	offsetof(ALARM_WINDOW_CONTROL_BLOCK,
			 alarm_window_alarm_add),		   /* control block */
	(void *)&alarm_window_alarm_add_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET alarm_window_vertical_scroll_9_define = {
	"vertical_scroll_9",
	GX_TYPE_VERTICAL_SCROLL, /* widget type                    */
	GX_ID_NONE,				 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_SCROLLBAR_RELATIVE_THUMB |
		GX_SCROLLBAR_VERTICAL,			 /* style flags */
	0,									 /* status flags                   */
	sizeof(GX_SCROLLBAR),				 /* control block size             */
	GX_COLOR_ID_BLACK,					 /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL,			 /* selected color id              */
	GX_COLOR_ID_BLACK,					 /* disabled color id              */
	gx_studio_vertical_scrollbar_create, /* create function                */
	GX_NULL,							 /* drawing function override      */
	GX_NULL,							 /* event function override        */
	{314, 80, 319, 339},				 /* widget size                    */
	GX_NULL,							 /* no next widget                 */
	GX_NULL,							 /* no child widgets               */
	offsetof(ALARM_WINDOW_CONTROL_BLOCK,
			 alarm_window_vertical_scroll_9),		   /* control block */
	(void *)&alarm_window_vertical_scroll_9_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET alarm_window_alarm_list_define = {
	"alarm_list",
	GX_TYPE_VERTICAL_LIST, /* widget type                    */
	GX_ID_NONE,			   /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		/* status flags                   */
	sizeof(GX_VERTICAL_LIST),		/* control block size             */
	GX_COLOR_ID_WINDOW_FILL,		/* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,		/* selected color id              */
	GX_COLOR_ID_WINDOW_FILL,		/* disabled color id              */
	gx_studio_vertical_list_create, /* create function                */
	GX_NULL,						/* drawing function override      */
	(UINT (*)(GX_WIDGET *,
			  GX_EVENT *))alarm_list_win_event, /* event function override */
	{40, 80, 319, 339},						/* widget size                    */
	GX_NULL,								/* no next widget                 */
	&alarm_window_vertical_scroll_9_define, /* child widget definition        */
	offsetof(ALARM_WINDOW_CONTROL_BLOCK,
			 alarm_window_alarm_list),			/* control block */
	(void *)&alarm_window_alarm_list_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET alarm_window_window_6_define = {
	"window_6",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS, /* status flags                   */
	sizeof(GX_WINDOW),		 /* control block size             */
	GX_COLOR_ID_GRAY,		 /* normal color id                */
	GX_COLOR_ID_GRAY,		 /* selected color id              */
	GX_COLOR_ID_GRAY,		 /* disabled color id              */
	gx_studio_window_create, /* create function                */
	GX_NULL,				 /* drawing function override      */
	(UINT (*)(GX_WIDGET *, GX_EVENT *))
		alarm_add_screen_event_handler, /* event function override */
	{0, 0, 359, 69},					/* widget size                    */
	&alarm_window_alarm_list_define,	/* next widget definition         */
	&alarm_window_alarm_add_define,		/* child widget definition        */
	offsetof(ALARM_WINDOW_CONTROL_BLOCK,
			 alarm_window_window_6),		  /* control block */
	(void *)&alarm_window_window_6_properties /* extended properties          */
};

GX_CONST GX_STUDIO_WIDGET alarm_window_define = {
	"alarm_window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT |
		GX_STYLE_ENABLED,				/* style flags */
	GX_STATUS_ACCEPTS_FOCUS,			/* status flags                   */
	sizeof(ALARM_WINDOW_CONTROL_BLOCK), /* control block size             */
	GX_COLOR_ID_WINDOW_FILL,			/* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,			/* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,			/* disabled color id              */
	gx_studio_window_create,			/* create function                */
	GX_NULL,							/* drawing function override      */
	(UINT (*)(GX_WIDGET *, GX_EVENT *))
		alarm_screen_event_handler,	 /* event function override */
	{0, 0, 359, 359},				 /* widget size                    */
	GX_NULL,						 /* next widget                    */
	&alarm_window_window_6_define,	 /* child widget                   */
	0,								 /* control block                  */
	(void *)&alarm_window_properties /* extended properties            */
};
GX_WINDOW_PROPERTIES window_2_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_VERTICAL_LIST_PROPERTIES window_2_vertical_list_properties = {
	0,			   /* wallpaper id                   */
	callback_name, /* callback function              */
	10			   /* total rows                     */
};
GX_WINDOW_PROPERTIES window_2_window_4_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_4_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_5_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};
GX_WINDOW_PROPERTIES window_2_window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};
GX_WINDOW_PROPERTIES window_2_window_1_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_1_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_1_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};
GX_WINDOW_PROPERTIES window_2_window_2_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_2_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_2_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};
GX_WINDOW_PROPERTIES window_2_window_3_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_3_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_3_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};
GX_WINDOW_PROPERTIES window_2_window_5_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_ICON_PROPERTIES window_2_icon_5_properties = {
	GX_PIXELMAP_ID_RADIO_ON, /* normal pixelmap id             */
	0						 /* selected pixelmap id           */
};
GX_PROMPT_PROPERTIES window_2_prompt_4_properties = {
	0,						   /* string id                      */
	GX_FONT_ID_PROMPT,		   /* font id                        */
	GX_COLOR_ID_TEXT,		   /* normal text color              */
	GX_COLOR_ID_SELECTED_TEXT, /* selected text color            */
	GX_COLOR_ID_DISABLED_TEXT  /* disabled text color            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_5_define = {
	"prompt_5",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 48, 223, 71},		   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt_5), /* control block */
	(void *)&window_2_prompt_5_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_4_define = {
	"icon_4",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 53, 123, 68},		   /* widget size                    */
	&window_2_prompt_5_define, /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon_4), /* control block */
	(void *)&window_2_icon_4_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_define = {
	"prompt",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 92, 223, 115},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt), /* control block */
	(void *)&window_2_prompt_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_define = {
	"icon",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 98, 123, 113},	   /* widget size                    */
	&window_2_prompt_define,   /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon), /* control block */
	(void *)&window_2_icon_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_1_define = {
	"prompt_1",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 138, 223, 161},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt_1), /* control block */
	(void *)&window_2_prompt_1_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_1_define = {
	"icon_1",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 143, 123, 158},	   /* widget size                    */
	&window_2_prompt_1_define, /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon_1), /* control block */
	(void *)&window_2_icon_1_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_2_define = {
	"prompt_2",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 183, 223, 206},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt_2), /* control block */
	(void *)&window_2_prompt_2_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_2_define = {
	"icon_2",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 188, 123, 203},	   /* widget size                    */
	&window_2_prompt_2_define, /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon_2), /* control block */
	(void *)&window_2_icon_2_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_3_define = {
	"prompt_3",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 228, 223, 251},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt_3), /* control block */
	(void *)&window_2_prompt_3_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_3_define = {
	"icon_3",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 233, 123, 248},	   /* widget size                    */
	&window_2_prompt_3_define, /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon_3), /* control block */
	(void *)&window_2_icon_3_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_prompt_4_define = {
	"prompt_4",
	GX_TYPE_PROMPT, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT | GX_STYLE_ENABLED |
		GX_STYLE_TEXT_CENTER,  /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_PROMPT),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_prompt_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{144, 273, 223, 296},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_prompt_4), /* control block */
	(void *)&window_2_prompt_4_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_icon_5_define = {
	"icon_5",
	GX_TYPE_ICON, /* widget type                    */
	GX_ID_NONE,	  /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED | GX_STYLE_HALIGN_LEFT |
		GX_STYLE_VALIGN_TOP,   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_ICON),		   /* control block size             */
	GX_COLOR_ID_WIDGET_FILL,   /* normal color id                */
	GX_COLOR_ID_SELECTED_FILL, /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_icon_create,	   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{108, 278, 123, 293},	   /* widget size                    */
	&window_2_prompt_4_define, /* next widget definition         */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_icon_5), /* control block */
	(void *)&window_2_icon_5_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_5_define = {
	"window_5",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 264, 273, 308},	   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	&window_2_icon_5_define,   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window_5), /* control block */
	(void *)&window_2_window_5_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_3_define = {
	"window_3",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 219, 273, 263},	   /* widget size                    */
	&window_2_window_5_define, /* next widget definition         */
	&window_2_icon_3_define,   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window_3), /* control block */
	(void *)&window_2_window_3_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_2_define = {
	"window_2",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 174, 273, 218},	   /* widget size                    */
	&window_2_window_3_define, /* next widget definition         */
	&window_2_icon_2_define,   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window_2), /* control block */
	(void *)&window_2_window_2_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_1_define = {
	"window_1",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 129, 273, 173},	   /* widget size                    */
	&window_2_window_2_define, /* next widget definition         */
	&window_2_icon_1_define,   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window_1), /* control block */
	(void *)&window_2_window_1_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_define = {
	"window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 84, 273, 128},		   /* widget size                    */
	&window_2_window_1_define, /* next widget definition         */
	&window_2_icon_define,	   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window), /* control block */
	(void *)&window_2_window_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_window_4_define = {
	"window_4",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,	   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{94, 39, 273, 83},		   /* widget size                    */
	&window_2_window_define,   /* next widget definition         */
	&window_2_icon_4_define,   /* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK, window_2_window_4), /* control block */
	(void *)&window_2_window_4_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_2_vertical_list_define = {
	"vertical_list",
	GX_TYPE_VERTICAL_LIST, /* widget type                    */
	GX_ID_NONE,			   /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		/* status flags                   */
	sizeof(GX_VERTICAL_LIST),		/* control block size             */
	GX_COLOR_ID_WINDOW_FILL,		/* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,		/* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,		/* disabled color id              */
	gx_studio_vertical_list_create, /* create function                */
	GX_NULL,						/* drawing function override      */
	GX_NULL,						/* event function override        */
	{94, 39, 273, 216},				/* widget size                    */
	GX_NULL,						/* no next widget                 */
	&window_2_window_4_define,		/* child widget definition        */
	offsetof(WINDOW_2_CONTROL_BLOCK,
			 window_2_vertical_list),		   /* control block */
	(void *)&window_2_vertical_list_properties /* extended properties         */
};

GX_CONST GX_STUDIO_WIDGET window_2_define = {
	"window_2",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		/* status flags                   */
	sizeof(WINDOW_2_CONTROL_BLOCK), /* control block size             */
	GX_COLOR_ID_WINDOW_FILL,		/* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,		/* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,		/* disabled color id              */
	gx_studio_window_create,		/* create function                */
	GX_NULL,						/* drawing function override      */
	GX_NULL,						/* event function override        */
	{0, 0, 359, 359},				/* widget size                    */
	GX_NULL,						/* next widget                    */
	&window_2_vertical_list_define, /* child widget                   */
	0,								/* control block                  */
	(void *)&window_2_properties	/* extended properties            */
};
GX_WINDOW_PROPERTIES status_window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_PIXELMAP_BUTTON_PROPERTIES status_window_pixelmap_button_properties = {
	GX_PIXELMAP_ID_WIFI, /* normal pixelmap id             */
	0,					 /* selected pixelmap id           */
	0					 /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES status_window_pixelmap_button_1_properties = {
	GX_PIXELMAP_ID_SOUND, /* normal pixelmap id             */
	0,					  /* selected pixelmap id           */
	0					  /* disabled pixelmap id           */
};
GX_PIXELMAP_BUTTON_PROPERTIES status_window_pixelmap_button_2_properties = {
	GX_PIXELMAP_ID_BLUETOOTH, /* normal pixelmap id             */
	0,						  /* selected pixelmap id           */
	0						  /* disabled pixelmap id           */
};

GX_CONST GX_STUDIO_WIDGET status_window_pixelmap_button_2_define = {
	"pixelmap_button_2",
	GX_TYPE_PIXELMAP_BUTTON, /* widget type                    */
	GX_ID_NONE,				 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		  /* status flags                   */
	sizeof(GX_PIXELMAP_BUTTON),		  /* control block size             */
	GX_COLOR_ID_BTN_LOWER,			  /* normal color id                */
	GX_COLOR_ID_BTN_UPPER,			  /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,		  /* disabled color id              */
	gx_studio_pixelmap_button_create, /* create function                */
	GX_NULL,						  /* drawing function override      */
	GX_NULL,						  /* event function override        */
	{130, 295, 158, 318},			  /* widget size                    */
	GX_NULL,						  /* no next widget                 */
	GX_NULL,						  /* no child widgets               */
	offsetof(STATUS_WINDOW_CONTROL_BLOCK,
			 status_window_pixelmap_button_2), /* control block */
	(void
		 *)&status_window_pixelmap_button_2_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET status_window_pixelmap_button_1_define = {
	"pixelmap_button_1",
	GX_TYPE_PIXELMAP_BUTTON, /* widget type                    */
	GX_ID_NONE,				 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		  /* status flags                   */
	sizeof(GX_PIXELMAP_BUTTON),		  /* control block size             */
	GX_COLOR_ID_BTN_LOWER,			  /* normal color id                */
	GX_COLOR_ID_BTN_UPPER,			  /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,		  /* disabled color id              */
	gx_studio_pixelmap_button_create, /* create function                */
	GX_NULL,						  /* drawing function override      */
	GX_NULL,						  /* event function override        */
	{173, 295, 201, 318},			  /* widget size                    */
	&status_window_pixelmap_button_2_define, /* next widget definition */
	GX_NULL, /* no child widgets               */
	offsetof(STATUS_WINDOW_CONTROL_BLOCK,
			 status_window_pixelmap_button_1), /* control block */
	(void
		 *)&status_window_pixelmap_button_1_properties /* extended properties */
};

GX_CONST GX_STUDIO_WIDGET status_window_pixelmap_button_define = {
	"pixelmap_button",
	GX_TYPE_PIXELMAP_BUTTON, /* widget type                    */
	GX_ID_NONE,				 /* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		  /* status flags                   */
	sizeof(GX_PIXELMAP_BUTTON),		  /* control block size             */
	GX_COLOR_ID_BTN_LOWER,			  /* normal color id                */
	GX_COLOR_ID_BTN_UPPER,			  /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,		  /* disabled color id              */
	gx_studio_pixelmap_button_create, /* create function                */
	GX_NULL,						  /* drawing function override      */
	GX_NULL,						  /* event function override        */
	{216, 297, 244, 320},			  /* widget size                    */
	&status_window_pixelmap_button_1_define, /* next widget definition */
	GX_NULL, /* no child widgets               */
	offsetof(STATUS_WINDOW_CONTROL_BLOCK,
			 status_window_pixelmap_button),		  /* control block */
	(void *)&status_window_pixelmap_button_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET status_window_define = {
	"status_window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT |
		GX_STYLE_ENABLED,				   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,			   /* status flags                   */
	sizeof(STATUS_WINDOW_CONTROL_BLOCK),   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,				   /* normal color id                */
	GX_COLOR_ID_BTN_TEXT,				   /* selected color id              */
	GX_COLOR_ID_BTN_TEXT,				   /* disabled color id              */
	gx_studio_window_create,			   /* create function                */
	GX_NULL,							   /* drawing function override      */
	GX_NULL,							   /* event function override        */
	{0, -1, 359, 358},					   /* widget size                    */
	GX_NULL,							   /* next widget                    */
	&status_window_pixelmap_button_define, /* child widget                   */
	0,									   /* control block                  */
	(void *)&status_window_properties	   /* extended properties            */
};
GX_WINDOW_PROPERTIES root_window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES root_window_main_window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES root_window_watch_face_window_properties = {
	0 /* wallpaper pixelmap id          */
};

GX_CONST GX_STUDIO_WIDGET root_window_watch_face_window_define = {
	"watch_face_window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,			   /* status flags                   */
	sizeof(GX_WINDOW),					   /* control block size             */
	GX_COLOR_ID_BTN_TEXT,				   /* normal color id                */
	GX_COLOR_ID_BTN_TEXT,				   /* selected color id              */
	GX_COLOR_ID_BTN_TEXT,				   /* disabled color id              */
	gx_studio_window_create,			   /* create function                */
	(VOID (*)(GX_WIDGET *))main_disp_draw, /* drawing function override      */
	(UINT (*)(GX_WIDGET *,
			  GX_EVENT *))main_disp_handler, /* event function override */
	{0, 0, 359, 359}, /* widget size                    */
	GX_NULL,		  /* no next widget                 */
	GX_NULL,		  /* no child widgets               */
	offsetof(ROOT_WINDOW_CONTROL_BLOCK,
			 root_window_watch_face_window),		  /* control block */
	(void *)&root_window_watch_face_window_properties /* extended properties  */
};

GX_CONST GX_STUDIO_WIDGET root_window_main_window_define = {
	"main_window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_TRANSPARENT |
		GX_STYLE_ENABLED,				   /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,			   /* status flags                   */
	sizeof(GX_WINDOW),					   /* control block size             */
	GX_COLOR_ID_WINDOW_FILL,			   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,			   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL,			   /* disabled color id              */
	gx_studio_window_create,			   /* create function                */
	GX_NULL,							   /* drawing function override      */
	GX_NULL,							   /* event function override        */
	{0, 0, 359, 359},					   /* widget size                    */
	GX_NULL,							   /* no next widget                 */
	&root_window_watch_face_window_define, /* child widget definition        */
	offsetof(ROOT_WINDOW_CONTROL_BLOCK,
			 root_window_main_window),			/* control block */
	(void *)&root_window_main_window_properties /* extended properties        */
};

GX_CONST GX_STUDIO_WIDGET root_window_define = {
	"root_window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,		   /* status flags                   */
	sizeof(ROOT_WINDOW_CONTROL_BLOCK), /* control block size             */
	GX_COLOR_ID_BTN_TEXT,			   /* normal color id                */
	GX_COLOR_ID_BTN_TEXT,			   /* selected color id              */
	GX_COLOR_ID_BTN_TEXT,			   /* disabled color id              */
	gx_studio_window_create,		   /* create function                */
	GX_NULL,						   /* drawing function override      */
	(UINT (*)(GX_WIDGET *, GX_EVENT *))root_event, /* event function override */
	{0, 0, 359, 359},				 /* widget size                    */
	GX_NULL,						 /* next widget                    */
	&root_window_main_window_define, /* child widget                   */
	0,								 /* control block                  */
	(void *)&root_window_properties	 /* extended properties            */
};
GX_WINDOW_PROPERTIES window_properties = {
	0 /* wallpaper pixelmap id          */
};
GX_WINDOW_PROPERTIES window_window_7_properties = {
	0 /* wallpaper pixelmap id          */
};

GX_CONST GX_STUDIO_WIDGET window_window_7_define = {
	"window_7",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_THIN | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,   /* status flags                   */
	sizeof(GX_WINDOW),		   /* control block size             */
	GX_COLOR_ID_WINDOW_FILL,   /* normal color id                */
	GX_COLOR_ID_WINDOW_FILL,   /* selected color id              */
	GX_COLOR_ID_DISABLED_FILL, /* disabled color id              */
	gx_studio_window_create,   /* create function                */
	GX_NULL,				   /* drawing function override      */
	GX_NULL,				   /* event function override        */
	{90, 88, 269, 267},		   /* widget size                    */
	GX_NULL,				   /* no next widget                 */
	GX_NULL,				   /* no child widgets               */
	offsetof(WINDOW_CONTROL_BLOCK, window_window_7), /* control block */
	(void *)&window_window_7_properties /* extended properties            */
};

GX_CONST GX_STUDIO_WIDGET window_define = {
	"window",
	GX_TYPE_WINDOW, /* widget type                    */
	GX_ID_NONE,		/* widget id                      */
#if defined(GX_WIDGET_USER_DATA)
	0, /* user data                      */
#endif
	GX_STYLE_BORDER_NONE | GX_STYLE_ENABLED, /* style flags */
	GX_STATUS_ACCEPTS_FOCUS,	  /* status flags                   */
	sizeof(WINDOW_CONTROL_BLOCK), /* control block size             */
	GX_COLOR_ID_BTN_TEXT,		  /* normal color id                */
	GX_COLOR_ID_BTN_TEXT,		  /* selected color id              */
	GX_COLOR_ID_BTN_TEXT,		  /* disabled color id              */
	gx_studio_window_create,	  /* create function                */
	GX_NULL,					  /* drawing function override      */
	GX_NULL,					  /* event function override        */
	{0, -2, 359, 357},			  /* widget size                    */
	GX_NULL,					  /* next widget                    */
	&window_window_7_define,	  /* child widget                   */
	0,							  /* control block                  */
	(void *)&window_properties	  /* extended properties            */
};
GX_CONST GX_STUDIO_WIDGET_ENTRY guix_simple_widget_table[] = {
	{&alarm_list_define, (GX_WIDGET *)&alarm_list},
	{&alarm_window_define, (GX_WIDGET *)&alarm_window},
	{&window_2_define, (GX_WIDGET *)&window_2},
	{&status_window_define, (GX_WIDGET *)&status_window},
	{&root_window_define, (GX_WIDGET *)&root_window},
	{&window_define, (GX_WIDGET *)&window},
	{GX_NULL, GX_NULL}};

static GX_WIDGET *gx_studio_nested_widget_create(
	GX_BYTE *control, GX_CONST GX_STUDIO_WIDGET *definition, GX_WIDGET *parent)
{
	UINT status = GX_SUCCESS;
	GX_WIDGET *widget = GX_NULL;
	GX_VALUE list_count = 0;
	GX_VALUE list_total_count = 0;

	if (parent && (parent->gx_widget_type == GX_TYPE_MENU)) {
		list_total_count = ((GX_MENU *)parent)->gx_menu_list_total_count;
	}

	while (definition && status == GX_SUCCESS) {
		if (definition->create_function) {
			if (definition->style & GX_STYLE_DYNAMICALLY_ALLOCATED) {
				status =
					gx_widget_allocate(&widget, definition->control_block_size);
				if (status != GX_SUCCESS) {
					return GX_NULL;
				}
			} else {
				if (control == GX_NULL) {
					return GX_NULL;
				}
				widget =
					(GX_WIDGET *)(control + definition->control_block_offset);
			}

			status = definition->create_function(definition, widget, parent);

			if (list_count < list_total_count) {
				gx_menu_insert((GX_MENU *)parent, widget);
				((GX_MENU *)parent)->gx_menu_list_total_count--;
				list_count++;
			}

			if (status == GX_SUCCESS) {
				if (definition->widget_type != GX_TYPE_TEMPLATE) {
#if defined(GUIX_5_4_0_COMPATIBILITY)
					gx_widget_fill_color_set(
						widget, definition->normal_fill_color_id,
						definition->selected_fill_color_id);
#else
					gx_widget_fill_color_set(
						widget, definition->normal_fill_color_id,
						definition->selected_fill_color_id,
						definition->disabled_fill_color_id);
#endif
				}

				if (!(definition->status & GX_STATUS_ACCEPTS_FOCUS)) {
					gx_widget_status_remove(widget, GX_STATUS_ACCEPTS_FOCUS);
				}

				if (definition->draw_function) {
					gx_widget_draw_set(widget, definition->draw_function);
				}
				if (definition->event_function) {
					gx_widget_event_process_set(widget,
												definition->event_function);
				}

#if defined(GX_WIDGET_USER_DATA)
				widget->gx_widget_user_data = definition->user_data;
#endif

				if (definition->child_widget) {
					gx_studio_nested_widget_create(
						control, definition->child_widget, widget);
				}
			}
			definition = definition->next_widget;
		}
	}
	return widget;
}

GX_WIDGET *gx_studio_widget_create(GX_BYTE *control,
								   GX_CONST GX_STUDIO_WIDGET *definition,
								   GX_WIDGET *parent)
{
	GX_WIDGET *widget;
	widget = gx_studio_nested_widget_create(control, definition, GX_NULL);

	if (parent && widget) {
		gx_widget_attach(parent, widget);
	}
	return widget;
}

UINT gx_studio_named_widget_create(char *name, GX_WIDGET *parent,
								   GX_WIDGET **new_widget)
{
	UINT status = GX_FAILURE;
	GX_CONST GX_STUDIO_WIDGET_ENTRY *entry = guix_simple_widget_table;
	GX_WIDGET *widget = GX_NULL;

	while (entry->widget_information) {
		if (!strcmp(name, entry->widget_information->widget_name)) {
			widget = gx_studio_widget_create((GX_BYTE *)entry->widget,
											 entry->widget_information, parent);
			if (widget) {
				status = GX_SUCCESS;
			}
			break;
		}
		entry++;
	}

	if (new_widget) {
		*new_widget = widget;
	}
	return status;
}

UINT gx_studio_display_configure(USHORT display, UINT (*driver)(GX_DISPLAY *),
								 GX_UBYTE language, USHORT theme,
								 GX_WINDOW_ROOT **return_root)
{
	GX_CONST GX_THEME *theme_ptr;
	GX_RECTANGLE size;

	GX_STUDIO_DISPLAY_INFO *display_info = &guix_simple_display_table[display];

	/* create the requested display */

	gx_display_create(display_info->display, display_info->name, driver,
					  (GX_VALUE)display_info->x_resolution,
					  (GX_VALUE)display_info->y_resolution);

	/* install the request theme */

	if (display_info->theme_table) {
		theme_ptr = display_info->theme_table[theme];
		if (theme_ptr) {
			gx_display_color_table_set(display_info->display,
									   theme_ptr->theme_color_table,
									   theme_ptr->theme_color_table_size);

			/* install the color palette if required */
			if (display_info->display->gx_display_driver_palette_set &&
				theme_ptr->theme_palette != NULL) {
				display_info->display->gx_display_driver_palette_set(
					display_info->display, theme_ptr->theme_palette,
					theme_ptr->theme_palette_size);
			}

			gx_display_font_table_set(display_info->display,
									  theme_ptr->theme_font_table,
									  theme_ptr->theme_font_table_size);
			gx_display_pixelmap_table_set(display_info->display,
										  theme_ptr->theme_pixelmap_table,
										  theme_ptr->theme_pixelmap_table_size);
			gx_system_scroll_appearance_set(
				theme_ptr->theme_vertical_scroll_style,
				(GX_SCROLLBAR_APPEARANCE *)&theme_ptr
					->theme_vertical_scrollbar_appearance);
			gx_system_scroll_appearance_set(
				theme_ptr->theme_horizontal_scroll_style,
				(GX_SCROLLBAR_APPEARANCE *)&theme_ptr
					->theme_horizontal_scrollbar_appearance);
			gx_display_language_table_set_ext(
				display_info->display, display_info->language_table,
				(GX_UBYTE)display_info->language_table_size,
				display_info->string_table_size);
			gx_display_active_language_set(display_info->display, language);
		}
	}

	/* create the canvas for this display */

	gx_canvas_create(
		display_info->canvas, display_info->canvas_name, display_info->display,
		GX_CANVAS_MANAGED | GX_CANVAS_VISIBLE, display_info->x_resolution,
		display_info->y_resolution, display_info->canvas_memory,
		display_info->canvas_memory_size);

	/* Create the root window for this canvas */

	gx_utility_rectangle_define(&size, 0, 0,
								(GX_VALUE)(display_info->x_resolution - 1),
								(GX_VALUE)(display_info->y_resolution - 1));

	gx_window_root_create(display_info->root_window, display_info->name,
						  display_info->canvas, GX_STYLE_NONE, 0, &size);
	if (return_root) {
		*return_root = display_info->root_window;
	}
	return GX_SUCCESS;
}
#undef GUIX_STUDIO_GENERATED_FILE
